### ISSUE TITLE
contextual values

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#337]
Currently we have no kind of support for threadlocals. I would like to introduce something that gives us threadlocals on the JVM, without actually introducing a notion of threads. I'm thinking of something like this:

    //declares a contextual value
    shared Contextual<Transaction> currentTransaction = Contextual<Transaction>();
    
    //initializes the contextual value and initiates work that uses it:
    try ( Context { currentTransaction->transactionManager.Transaction() } ) {
        doSomeWork();
    }
    
    //use the contextual value
    void doSomeWork() {
        Transaction tx = currentTransaction.get();
        ...
    }

Perhaps it would be better to make `Contextual<T>` a subtype of `T()`, letting you write:

    Transaction tx = currentTransaction();

Like we do with metamodel stuff.

So I think I can pretty quickly implement the JVM side of this. @chochos do you have time to work on the JS?

**Comment by quintesse** [comment]
I had some difficulty trying to implement the API suggested in this issue so after some brainstorming on Gitter (https://gitter.im/ceylon/user?at=5523e7b54ba0f4ec45d1fb10) @jvasileff came up with the following much simpler design which I think is just as useful:

```ceylon
shared class Contextual<Element>() {
    value threadLocal = ThreadLocal<Element>();
    
    shared Element get() {
        assert (is Element result = threadLocal.get());
        return result;
    }
    
    shared class Using(Element|Element() e)
            satisfies Obtainable {
        
        shared actual void obtain() {
            if (is Element() e) {
                threadLocal.set(e());    
            }
            else {
                threadLocal.set(e);
            }
        }
        
        shared actual void release(Throwable? error)
                => threadLocal.remove();
    }
}
```

which could be used like this:

```ceylon
shared Contextual<String> stringValue = Contextual<String>();
shared Contextual<Integer> intValue = Contextual<Integer>();
shared void useContextual() {
    try (stringValue.Using("a"), intValue.Using(1)) {
        print(stringValue.get());
        print(intValue.get());     
    }
}
```

What do you think @gavinking ?

**Comment by quintesse** [comment]
Edit: changed code to remember and restore previous value on `release()` so we can nest the try-resource statements. The test code will now return:

```
a
1
2
1
```

**Comment by chochos** [comment]
You can't add this to the language module, since it uses a `ThreadLocal` which would add a dependency on `java.base` which would make it jvm-only.

**Comment by quintesse** [comment]
Of course not, it's just to see what the design would look like ;)
We would need a separate implementation for the JVM and JS.
I imagine that for JS it's nothing more than defining some global map somewhere and then adding/removing items to/from it, right?

**Comment by chochos** [comment]
I guess. Well maybe not global, but something local to the module or something (global vars are considered a Bad Thing™)

**Comment by jvasileff** [comment]
The instance of `Contextual` defines the scope, right? And in Java, the combination of the instance and the thread. In other words, wouldn't it just be replacing `threadLocal` with a map?

**Comment by chochos** [comment]
not even a map, just a variable.

**Comment by quintesse** [comment]
> but something local to the module or something (global vars are considered a Bad Thing™)

Sure, I guess that practically speaking with JavaScript's lack of threading you can't access that map/variable directly anyway and if you have a toplevel `Contextual` like

```ceylon
shared Contextual<Foo> foo = Contextual<Foo>();
```

it can at least access the map/variable that exists in the module for you.

So in the case of the JavaScript backend this just becomes a weirdly complex way to set a toplevel variable ;)

**Comment by FroMage** [comment]
Moving to 1.3.

**Comment by quintesse** [comment]
I have a working implementation for this for both backends using `native`. @gavinking if you give the okay for the design mentioned here https://github.com/ceylon/ceylon.language/issues/337#issuecomment-90747456 I can add it to the language module ASAP.

**Comment by quintesse** [comment]
I was of course not able to implement the suggestion to make `Contextual<T>` a subtype of `T()` because ceylon/ceylon-spec#844 is still open.

**Comment by gavinking** [comment]
Hrm. So I think that design is pretty elegant. The only doubt I have is that it doesn't quite address every usecase I had in mind with my original proposal (it doesn't let you have a context which is shared between multiple threads). But I guess that's fine. Surely it gives you the basic primitive you need to be able to implement the more advanced things I was thinking of.

So fine. Merge it.

**Comment by quintesse** [comment]
Ok, I added the implementation but it doesn't have any documentation yet.

**Comment by gavinking** [comment]
Documentation is for sissies!

**Comment by quintesse** [comment]
Ok, added docs so I'll close this now but please take a look @gavinking because I'm sure you'll want to change the wording ;)
