### ISSUE TITLE
formatFloat() is missing

### ISSUE THREAD

**Issue by ObamaB** [ceylon/ceylon.language#343]
There exist parseInteger(), formatInteger() and parseFloat(),
but formatFloat() is missing completely.
Additionally, ceylon.math.float should allow some roundings and ceylon.math should be usable in JavaScript.

**Comment by gavinking** [comment]
FTR: I have added a simple `formatFloat()` function to the language module in Ceylon 1.2. It can't do anything fancy, just basic handling of decimal places.
