### ISSUE TITLE
should we allow floats to be compared to integers

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#453]
It would be nice if both `Float` and `Integer` were `Comparable<Float|Integer>`.

**Comment by ePaul** [comment]
When implementing this, care should be taken similar to the equality issue at #758, because there can be several Integer values between two Float values.

I.e. make sure that `922337203685477633.compareTo(9.2233720368547763E17)` gives `larger`, not `equal` (as the naive implementation would do).

**Comment by jvasileff** [comment]
Yeah, with the screwy nature of equality for large numbers, it doesn't seem possible to satisfy the `Comparable` contract. There would be unequal numbers where neither is larger than the other.

**Comment by gavinking** [comment]
So should I just close this issue?

**Comment by jvasileff** [comment]
I think so, unless I'm missing something.

**Comment by gavinking** [comment]
Good enough for me.

**Comment by ePaul** [comment]
Actually, I think it is possible to implement a order relation between Float and Integer, it will just be a lot less performant than simple comparison inside each type. (Though it cannot be consistent to equals with the restriction we just did build in #762.)

**Comment by gavinking** [comment]
Right, that was @jvasileff's point: if it's not consistent with `equals()`, then it violates the contract of `Comparable`. Given that, I just don't think this issue is worth it.
