### ISSUE TITLE
Add `AnnotatedDeclaration.isAnnotated(ClosedType<Annotation> annotations)`

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#460]
Should be cheaper than getting the annotation instances.

**Comment by tombentley** [comment]
`AnnotatedDeclaration` does not include `Import` (which is not a `Declaration`), so maybe putting it on `Annotated` makes more sense? (OTOH, it's AnnotatedDeclaration which currently has the `annotations()` method).

For that existing `annotations<out Annotation>()` method we pass the annotation type as a type argument, not as a type model value argument. So for consistency maybe it should be 

    import ceylon.language{AnnotationType = Annotation}
    shared interface Annotated {
        shared formal Boolean isAnnotated<Annotation>() 
            given Annotation satisfies AnnotationType;
    }

?

**Comment by FroMage** [comment]
Yes, sounds good.

**Comment by tombentley** [comment]
Hmm. We've avoided the whole `is*` naming convention in the language module so far, so I suppose the method should be `annotated<Annotation>()`.

**Comment by tombentley** [comment]
This is now implemented for JVM, just needs implementing for JS.
