### ISSUE TITLE
Parameter declarations are found twice by the metamodel

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.language#566]
```ceylon
import ceylon.language.meta.declaration {
    ValueDeclaration
}

class C(a) {
    shared Anything a;
}
shared void run() {
    for (option in `class C`.declaredMemberDeclarations<ValueDeclaration>()) {
        print(option);
    }
}
```
> value tmp::C.a
value tmp::C.a

Found while working on ceylon/ceylon.formatter#91 – the `SparseFormattingOptions` attributes are all parameters.

**Comment by davidfestal** [comment]
@tombentley : is it possible to revert commit ceylon/ceylon-compiler@82d658c and fix ceylon/ceylon.language#566 in another way ? In typechecked sources, parameters of methods (as well as non-shared parameters of a class) *are* members of the class or method.
This is for ceylon/ceylon-ide-eclipse#1324

**Comment by tombentley** [comment]
@davidfestal I've pushed a change, does it work for you?

**Comment by gavinking** [comment]
I confirm it's fixed.

**Comment by gavinking** [comment]
Thanks, @tombentley.
