### ISSUE TITLE
Comparison between three values at the same time does not compile when one value comes from a Tuple

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon.language#569]
```ceylon
function timer() {
    return [10, "Hi"];
}
    
assert(0 < timer().first < 10);
```

The code above fails to compile in the `assert` line due to:

```
Cannot find symbol
 symbol:   method longValue()
  location: class java.lang.Object
```

If we use three numbers, as in `0 < 4 < 10`, it works.

**Comment by lucaswerkmeister** [comment]
> This one also causes the same error:
> ```ceylon
> value ints = {1,2,3};
> print("min is ``min(ints)``");
> ```

That was reported as ceylon/ceylon-compiler#2089 and fixed by @tombentley. This appears to also have fixed `print("Time was ``timer().first``");`; the original issue, three-way comparison, remains unfixed though.

**Comment by tombentley** [comment]
It's a compiler bug, I've openned ceylon/ceylon-compiler#2096
