### ISSUE TITLE
Constructor metamodels

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#583]
We need to support constructor metamodel for ceylon/ceylon-spec#796. I think this summarizes what we're going to need:

* [ ] interface `ConstructorDeclaration`
* [ ] JVM impl of `ConstructorDeclaration`
* [x] JS impl of `ConstructorDeclaration`
* [ ] interface `Constructor`
* [ ] JVM impl of `Constructor`
* [x] JS impl of `Constructor`
* [ ] Changes to `Class`:
    * [ ] add `getDeclaredConstructor()`
    * [ ] add `getDeclaredConstructors()`
    * [ ] change `apply()` and `namedApply()` to support class instantiation via constructors
* [ ] Changes to `ClassDeclaration`:
    * [ ] add `annotatedDeclaredConstructorDeclarations()`
    * [ ] add `declaredConstructorDeclarations()`
    * [ ] add `getDeclaredConstructorDeclaration()`
    * [ ] if required, change `instantiate()` to support class instantiation via constructors
* [ ] Change `annotations()`, `optionalAnnotation()` and `sequencedAnnotations()` to support constructors
* [ ] Check we can read annotations on constructors and their parameters at runtime

**Comment by gavinking** [comment]
@tombentley is this issue done? can we close it now?

**Comment by tombentley** [comment]
Let close it.

**Comment by jvasileff** [comment]
I had some trouble using this api and thought I'd share my notes here. I can open separate issues/requests if that would help.

* It would be nice to have a consolidated API for discovering initializers, regardless of the way they are defined. AFAICT, for classes with initializer declarations, you discover the constructor by `is`-testing the `Class<T>` and check for annotations with `clazz.declaration.annotations<>()`. And for classes with constructors, you discover constructors through `ClassDeclaration.annotatedConstructorDeclarations()`. So I have to repeat myself, or write my own abstraction.
* `Class` has `getConstructor`, but no `getConstructors` (plural) with filters that would be analogous to `ClassOrInterface.getAttributes`.
* NPE on ``print(type(`MyClass.OneArg`))``. Having non-working reified tests foils my attempt at using the declaration to discover a constructor, and then using `Class.getConstructor` followed by an `assert` to what I know it to be.
* CCE on `` `MyClass`.declaration.annotatedConstructorDeclarations<SharedAnnotation>()``
* `Class.getConstructor<Arguments>` lets me put whatever I want in for `Arguments`. To be consistent with `ClassOrInterface.getMethod` and `ClassOrInterface.getAttribute` it should throw `IncompatibleTypeException` if you guess wrong. (But why not return null for all of them?)
* Doc for `ClassDeclaration.defaultConstructorDeclaration` says: "The default constructor is the one with the same name as its containing class."
* I don't see anything about `sealed`. Is the correct approach to explicitly check constructors (or class w/init params) for this annotation?

This is on the JVM. I haven't tried JS.

**Comment by gavinking** [comment]
@jvasileff some of those things like like definite bugs. But this issue is closed, so they'll be lost here!

**Comment by tombentley** [comment]
Yes, @jvasileff please open issues for each of these. btw, I agree that we should abstract over the diff between classes with parameter lists and those with a default constructor.

**Comment by gavinking** [comment]
> btw, I agree that we should abstract over the diff between classes with parameter lists and those with a default constructor.

I'm not completely in agreement with that. Default constructors can have annotations, and eventually will even be allowed to have a different visibility to their class.

**Comment by tombentley** [comment]
Well that's true, but it seems weird when the language itself abstracts over them. 

Surely we present a callable `ClassModel` for a class with a default constructor, and in the case that it's not `shared` we can make it take nothing as it's argument list type. That would be a little annoying when the non-`shared` constructor is visible to you, but it would help in the majority of cases.

**Comment by gavinking** [comment]
Sure but we already do that, don't we?

**Comment by gavinking** [comment]
> Sure but we already do that, don't we?

Ah, I apologize. No, we _don't_ do that yet, and that's the fault of the typechecker. The spec already says we should.

**Comment by gavinking** [comment]
Ack, my bad: we _do_ do it, just like the spec says we should.

**Comment by jvasileff** [comment]
Ok, I opened issues for most of these. I have no idea how `sealed` should factor in, so I left that one alone.

For the initializer abstraction, I was thinking something like:

    clazz.getInitializers<Arguments>(Type<Annotation>[] annotationTypes)

that would de-dup the default constructor and provide a unified way of discovering ways to instantiate classes. Perhaps some addition to this to filter out constructors that can't be invoked due to `shared` and `sealed` rules.

But I know this isn't a popular idea, so I won't open an issue for it unless there is more interest.

**Comment by jvasileff** [comment]
> present a callable ClassModel for a class with a default constructor

I'm finding this confusing/error prone, since if you use a `ClassModel` as a proxy for a `Constructor`, you silently lose the constructor's annotations.

It seems that the correct pattern is:

1. Search `Constructor`s for one that you want (zero arg or whatever)
2. If there were no constructors in step 1, use that as evidence that the class has an initialization parameter list, and consider the `Class` as a candidate initializer.

FWIW, the abstraction I'm currently using is:

```ceylon
shared
class Initializer<out Type=Anything, in Arguments=Nothing>(model) {
    shared
    Constructor<Type, Arguments> |
        Class<Type, Arguments> model;

    function cast<T>(Anything t) {
        assert(is T t);
        return t;
    }

    shared
    Class<Type, Nothing> classModel
        =>  switch (model)
            case (is Class<Type, Arguments>)
                model
            else
                cast<Class<Type, Nothing>>
                    (model.container);

    shared
    ClassDeclaration classDeclaration
        =>  switch (model)
            case (is Class<Type, Arguments>)
                model.declaration
            else
                model.declaration.container;

    shared
    ConstructorDeclaration | ClassDeclaration declaration
        =>  switch (model)
            case (is Class<Type, Arguments>)
                model.declaration
            else
                model.declaration;
}
```
