### ISSUE TITLE
Support for conversion ceylon sequential to native js array.

### ISSUE THREAD

**Issue by eugenpp** [ceylon/ceylon.language#594]
Currently is conversion supported only for Tuple type.

```
//Ceylon
shared String[] names = ["one", "two"];

// JS - names is backed by Tuple.
// so we can use nativeArray function to convert into js array
var nativeJsArray = getNames().nativeArray()
```

Another example where nativeArray is missing.
```
//Ceylon
shared String[] names = {"one", "two"}.sequence();

// JS - names is backed by ArraySequence.
// where nativeArray function is missing
var nativeJsArray = getNames().nativeArray() // RUNTIME ERROR
```

It should be supported for all sequential types.

**Comment by gavinking** [comment]
It seems that we're not doing this one. However I wonder it seems like `Tuple` should not expose its `nativeArray()` method. @chochos isn't that a problem?

Anyway, I'm closing this issue.

**Comment by chochos** [comment]
`Tuple.nativeArray()` is only used in an internal method of the js language module. I can modify `nativeArray` to return a copy (using `slice(0)`) instead of returning its internal array, to avoid any problems with the internal structure of the Tuple.
