### ISSUE TITLE
apply() with variadic metamodels

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#599]
The documentation of `Applicable.apply()` says:

> This has the same behaviour as invoking the applicable directly, but exchanges compile-time type
     safety with runtime checks.

But given 

    shared void star1(String* s1) {}

I can do

    `star1`();

but if I try 

    `star1`.apply();

I get `InvocationException` ("Not enough arguments to function. Expected 1 but got only 0").

Same is true of `Class` and `Constructor` models.

**Comment by FroMage** [comment]
Fixed by #607.
