### ISSUE TITLE
Integer/Float equals violates constract of Object.equals

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#602]
assert(9223372036854775807==9223372036854775807.0);
    assert(9223372036854775807==9223372036854775806.0);
    print("oops");

By the contract of `Object.equals` I may thus assume `9223372036854775807.0 == 9223372036854775806.0` because `==` is supposed to be transitive.

**Comment by tombentley** [comment]
> But it's the VM itself which considers these equalities correct.

That's not true, actually. The JVM has distinct opcodes for long and double comparison. You're referring to the fact that Java requires widening primitive conversion from `long` to `double`. Note that the boxed primitives `Double` and `Long` do have equality with instances of the other type.

What gets me is that because our `Integer` and `Float` are not identifiable, coupled with this semantic for `==` means I cannot tell them apart without resorting to `is`. And this semantic has knock-on effects for maps and sets, so even if I do define my preferred relation to be:

    if (x==y) {
        if (x is Float && y is Integer 
          || y is Float && x is Integer) {
            return false;
        }
        return true;
    }
    return false;
    }

I still can't easily use that definition with a hashmap.

**Comment by gavinking** [comment]
I still think this is the right thing, though I recognize that there are arguments on both sides. I'm going to close this issue, however. Sorry, Tom.

**Comment by jvasileff** [comment]
One strange thing in the API is that `Set.intersection` assumes a same-type requirement for equality, so with `Integer`s and `Float`s, two non-empty and equal sets may have an empty intersection:

```ceylon
    value ints = HashSet { 1 };
    value floats = HashSet { 1.0 };

    print(ints.union(ints));            // { 1 }
    print(ints.union(floats));          // { 1.0 }
    
    print(ints.intersection(ints));     // { 1 }
    print(ints.intersection(floats));   // {}

    print(ints == HashSet { 1 });   // true
    print(ints == floats);          // true
```

I guess technically, it's `Set.intersection` that is in the wrong here.

**Comment by gavinking** [comment]
@jvasileff Hrm. That's a _really_ good point that had not occurred to me. :-/
