### ISSUE TITLE
Variance problem in FunctionDeclaration.memberApply

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon.language#609]
This code:
```ceylon
Method<Nothing,Anything,Nothing> methodRef =
               `function method`.memberApply<Nothing,Anything,Nothing>(type(this),`T`);
```

Does not work. It complains that the type(this) does not match Type<Nothing>

**Comment by FroMage** [comment]
Fixed.

**Comment by FroMage** [comment]
@chochos can you confirm that I didn't mess up with the JS changes?

**Comment by chochos** [comment]
you only modified the declaration of native methods in Ceylon code and they compile OK.

**Comment by FroMage** [comment]
Does this mean it's enough?

**Comment by chochos** [comment]
Yes, it's enough.

**Comment by FroMage** [comment]
Thanks
