### ISSUE TITLE
ArrayStoreException on Tuple.initial and Tuple.terminal

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#618]
Both of the lines below result in an ArrayStoreException in Tuple.java:

```ceylon
shared void arrayStoreException() {
    value tuple = ["x", "y"];
    print(tuple.initial(1)); // error
    print(tuple.terminal(1)); // error
}
```

I must be missing something; the code looks ok to me:

```java
    @Override @Ignore
    public Sequential<? extends Element> terminal(long length) {
        if (length<=0) return (Sequential<? extends Element>) empty_.get_();
        if (length>=array.length) return this;
        int len = (int) length;
        Object[] initialArray = new Object[len];
        System.arraycopy(array, array.length-len, initialArray, 0, len); // <<< exception here
        return new Tuple($reifiedElement, initialArray);
    }
```

**Comment by lucaswerkmeister** [comment]
> ```java
Object[] initialArray = new Object[len];
```

Dang, that’s evil. Only the Eclipse source hover reveals that this refers to `ceylon.language.Object`, while `array` is an array of `java.lang.Object` :P

**Comment by lucaswerkmeister** [comment]
(`ceylon.language.String` is erased to `java.lang.String`, that’s why it doesn’t work)

**Comment by jvasileff** [comment]
> Dang, that’s evil

Indeed it is, @lucaswerkmeister!

So that makes it easy to find the other failure cases:

```ceylon
    value tuple = [2, 1, 2];
    tuple.trim((x) => x > 1);
    tuple.trimLeading((x) => x > 1);
    tuple.trimTrailing((x) => x > 1);
```

`String` erasure aside, it appears that nothing actually extends `ceylon.language.Object`, making these methods fail regardless of the element type.

**Comment by lucaswerkmeister** [comment]
> it appears that nothing actually extends ceylon.language.Object

Huh, I thought regular Ceylon classes did, but you’re right, they don’t.
TIL…

**Comment by gavinking** [comment]
Damn, OK, so yeah, I suck, thanks for noticing :-/
