### ISSUE TITLE
Possible serialization problem?

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon.language#620]
When running the entire test suite with the option `-Dceylon.compile.forceBoxedLocals` (see ceylon/ceylon-compiler#1464) I got 2 failing serialization tests: `testSerializationRegisterTwice2` and `testSerializationRegisterTwice3`. You can easily test this yourself with the latest code from master by making the following change to the code (using `testSerializationRegisterTwice3` as an example):

```ceylon
shared void testSerializationRegisterTwice3() {
    value sc = serialization();
    variable value id = 0;
    @boxed value instance = 1;
    sc.reference(0, instance);
    sc.reference(1, instance);
}
```

To see the difference in generated code, this is the original (unboxed):

```java
public static void testSerializationRegisterTwice3() {
    final .ceylon.language.serialization.SerializationContext sc = .ceylon.language.serialization.serialization_.serialization();
    long id = 0L;
    final long instance = 1L;
    sc.<.ceylon.language.Integer>reference(.ceylon.language.Integer.$TypeDescriptor$, .ceylon.language.Integer.instance(0L), .ceylon.language.Integer.instance(instance));
    sc.<.ceylon.language.Integer>reference(.ceylon.language.Integer.$TypeDescriptor$, .ceylon.language.Integer.instance(1L), .ceylon.language.Integer.instance(instance));
}
```

And this is the version with forced boxing:

```java
public static void testSerializationRegisterTwice3() {
    final .ceylon.language.serialization.SerializationContext sc = .ceylon.language.serialization.serialization_.serialization();
    long id = 0L;
    final .ceylon.language.Integer instance = .ceylon.language.Integer.instance(1L);
    sc.<.ceylon.language.Integer>reference(.ceylon.language.Integer.$TypeDescriptor$, .ceylon.language.Integer.instance(0L), instance);
    sc.<.ceylon.language.Integer>reference(.ceylon.language.Integer.$TypeDescriptor$, .ceylon.language.Integer.instance(1L), instance);
}
```

The error is just a generic assert:

    java.lang.AssertionError: A different instance has already been registered with id 1: "0", "1"

**Comment by tombentley** [comment]
The test now fails with this:

java.lang.AssertionError: The instance "1" has already been registered with id 1: You cannot register "1.0" again with a different id	11:01
	at com.redhat.ceylon.compiler.java.runtime.serialization.SerializationContextImpl.reference(SerializationContextImpl.java:73)	11:01
	at serialization.testSerializeBasics_.testSerializeBasics(serialization.ceylon:19)	11:01


That's due to #602. Basically I'd like the API to prevent doing broken things like registering the same object multiple times but with different ids (that would be a bug in the serialization library). But because Integer and Float are not identifiable, but also a Float can equal an Integer, I can't tell them apart easily. I suppose I can fix it by having a different map for each of them, that just seems surprisingly complicated.

**Comment by gavinking** [comment]
@tombentley I think there's something a bit heavy-handed here. One thing I tried to do was merge multiple json documents into the same `DeserializationContext`, but this failed, because there was one object repeated between the two documents. This seems to me a common-enough usage that it needs to be supported.

**Comment by tombentley** [comment]
>  One thing I tried to do was merge multiple json documents into the same `DeserializationContext`

You mean you took the output of two different serializations and merged them together?

**Comment by gavinking** [comment]
Yes.

**Comment by tombentley** [comment]
Well there's another excellent reason that won't work: Different instances will be allocated the same ids during serialization.

**Comment by gavinking** [comment]
No, this is deserialization. They already have ids.

**Comment by tombentley** [comment]
Yes, but unless you carefully renumbered stuff they'll both be using id `1` for different instance.

**Comment by gavinking** [comment]
I don't want two instances. I just want to ignore one definition.

**Comment by tombentley** [comment]
You seriously think that's a common enough thing to want to do that we should support it? It seems to me that the chances are slim that the types of things with id `x` will necessarily be compatible, so we'll likely just throw later during serialization with an `IncompatibleTypeException`, or something.

**Comment by gavinking** [comment]
It's *extremely* common in client/server systems.

**Comment by gavinking** [comment]
P.S. See `EntityManager.merge()` which exists precisely for this reason.

**Comment by tombentley** [comment]
@gavinking I've changed jsonsl to support this, if you want to try it out. We still throw in the case of duplicate ids during serialization though.

**Comment by gavinking** [comment]
@tombentley When I run the language module test suite I get:

```
[ceylon-run] Exception in thread "main" java.lang.reflect.InvocationTargetException
[ceylon-run] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-run] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ceylon-run] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-run] 	at java.lang.reflect.Method.invoke(Method.java:483)
[ceylon-run] 	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
[ceylon-run] 	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
[ceylon-run] 	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
[ceylon-run] 	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
[ceylon-run] Caused by: ceylon.language.AssertionError "The instance "1" has already been registered with id 1: You cannot register "1.0" again with a different id"
[ceylon-run] 	at com.redhat.ceylon.compiler.java.runtime.serialization.SerializationContextImpl.reference(SerializationContextImpl.java:73)
[ceylon-run] 	at serialization.testSerializeBasics_.testSerializeBasics(serialization.ceylon:19)
[ceylon-run] 	at serialization.run_.run(serialization.ceylon:209)
[ceylon-run] 	at serialization.run_.main(serialization.ceylon)
[ceylon-run] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-run] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ceylon-run] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-run] 	at java.lang.reflect.Method.invoke(Method.java:483)
[ceylon-run] 	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
[ceylon-run] 	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
[ceylon-run] 	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
[ceylon-run] 	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
[ceylon-run] 	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
[ceylon-run] 	at ceylon.modules.Main.execute(Main.java:69)
[ceylon-run] 	at ceylon.modules.Main.main(Main.java:42)
[ceylon-run] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ceylon-run] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ceylon-run] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ceylon-run] 	at java.lang.reflect.Method.invoke(Method.java:483)
[ceylon-run] 	at org.jboss.modules.Module.run(Module.java:312)
[ceylon-run] 	at org.jboss.modules.Main.main(Main.java:460)
[ceylon-run] 	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:215)
[ceylon-run] 	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:409)
[ceylon-run] 	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:346)
```

**Comment by FroMage** [comment]
This has been there for way too long, preventing the tests from running. Please either fix this or disable the tests.
