### ISSUE TITLE
Duplicates in declaredMemberDeclarations

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon.language#622]
Initializer parameters are returned twice when querying declared value members:

````ceylon
class Prueba(String s) {
  shared String a = s;
  shared String b => s;
}

`class Prueba`.declaredMemberDeclarations<ValueDeclaration>()
````
prints `[value Prueba.s, value Prueba.a, value Prueba.b, value Prueba.s]`

**Comment by lucaswerkmeister** [comment]
Dupe of #617 and #566?

**Comment by tombentley** [comment]
Yes, dupe. Closing.
