### ISSUE TITLE
JavaRunnerImpl throws when used with "ceylon war --exclude-module"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#633]
In some cases, I'm not sure which, JavaRunnerImpl complains about missing modules. So if you build a war with:

```sh
ceylon war \
  --exclude-module javax.servlet \
  --exclude-module org.apache.openejb:javaee-api \
  --exclude-module commons-codec:commons-codec \
  com.example.myModule
```

you might get:

```
   [tomcat] Caused by: java.lang.RuntimeException: Missing module: commons-codec:commons-codec/1.9
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.loadModule(JavaRunnerImpl.java:212)
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.loadModule(JavaRunnerImpl.java:224)
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.impl.JavaRunnerImpl.<init>(JavaRunnerImpl.java:65)
   [tomcat] 	at com.redhat.ceylon.compiler.java.runtime.tools.CeylonToolProvider.getRunner(CeylonToolProvider.java:27)
   [tomcat] 	at com.redhat.ceylon.war.WarInitializer.initialize(WarInitializer.java:85)
```

`JavaRunnerImpl` seems to care less about missing Ceylon modules than maven modules, since excluding `javax.servlet` (from Herd) does work. Or maybe it has something to do with transitive dependencies, since excluding `org.apache.openejb:javaee-api` (which is a dependency of `log4j`) seems to be ok. I dunno.

**Comment by FroMage** [comment]
I think the `war --exclude-module` only has an effect on the war itself: it will not insert the module inside the war, but the runtime will still require those modules to exist, and throw if they don't. So it's a way to say "these modules are provided and will be present at runtime". If the module is optional and not present, the runtime will not throw. I assume they are required and thus it throws. So this seems to be correct behaviour. I will change the help for the `--exclude-module` option to make this more explicit.

**Comment by FroMage** [comment]
Done.
