### ISSUE TITLE
Strange words in ceylon doc

### ISSUE THREAD

**Issue by NikNik77771** [ceylon/ceylon.language#635]
I investigate a Ceylon source code precisely to understand useful patterns. I am a not native English user, so I have to use dictionary. For my surprise Ceylon doc contains a lot of words that I am not able to find in dictionaries. I decided to open this issue, because it is regular. Unfortunately now I remember only one case.

In Iterrable:
"That is, for any given element of the stream, every iterator of the stream must eventually return the element, even if the iterator itself is not exhaustable." 
Exhaustable is something not understandable for not native speaker.

**Comment by tombentley** [comment]
It's a typo for exhaustible (
http://dictionary.reference.com/browse/exhaustible)

**Comment by NikNik77771** [comment]
Do you use spell checker?

**Comment by quintesse** [comment]
I guess this can be closed?
