### ISSUE TITLE
String.split returns {String*} instead of {String+}

### ISSUE THREAD

**Issue by marvelous** [ceylon/ceylon.language#638]
Is there a situation where `String.split` returns empty? Otherwise, please change the signature to `{String+}`.
I found out when using ceylon.ast.core:

    FullPackageName(name.split('.'.equals).map(lidentifier).sequence())

**Comment by gavinking** [comment]
@marvelous Well, yes, it returns `[]` for the empty string `""`.

However, upon reflection, I'm not sure that that's quite correct. I mean if `".".split(".".contains)` returns two empty strings, wouldn't it be more correct for  `"".split(".".contains)` to return one empty string?

**Comment by marvelous** [comment]
print("".split().sequence().size);
prints 1, which is indeed more correct.

**Comment by gavinking** [comment]
So Java's `"".split("\\.")` returns a single token.

On the other hand Java's `StringTokenizer` never returns empty strings as tokens.

**Comment by gavinking** [comment]
@marvelous oh, oops, you're right! it does return a token! Phew!

**Comment by gavinking** [comment]
@marvelous Thanks, fixed.
