### ISSUE TITLE
Need some easy way to get indices for typeArguments

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon.language#640]
The metamodel's Generic interface exposes a typeArguments element for getting type arguments. These are indexed on TypeParameter objects, which are rather hard to acquire. You actually have to go to the declaration object at the moment and get a TypeParameter by index from there.

We discussed possibly adding a syntax like this:
```ceylon
`given List.Element`
```

To fetch the Element type parameter from the list class.

**Comment by gavinking** [comment]
I don't want to add a new syntax at this stage, but I agree that the API should support better ways to obtain the indices of type parameter metamodel objects.

**Comment by tombentley** [comment]
Dupes of #621
