### ISSUE TITLE
Suspect defaulted methods in `Singleton`

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon.language#643]
In the `Singleton` class the methods :
* `iterator` 
* `findLast`

are defaulted an this would allow to implement broken `Sequence`
(thank you @lucaswerkmeister for the analysis)

**Comment by gavinking** [comment]
I dont see any good reason for them to be declared default.

**Comment by lucaswerkmeister** [comment]
Example:
```ceylon
class Multiton(String e, String f) extends Singleton<String>(e) {
    shared variable Boolean lie = false;
    shared actual Iterator<String> iterator()
            => lie then [f].iterator() else [e].iterator();
    shared actual String? findLast(Boolean selecting(String e))
            => lie then f else e;
}

shared void run() {
    Multiton m = Multiton("Hello", "Bye");
    String[] s = m;
    print("``[for (e in s) e]``, `` s.findLast((e) => true) else "null" ``");
    m.lie = true;
    print("``[for (e in s) e]``, `` s.findLast((e) => true) else "null" ``");
}
```
This prints

>     [Hello], Hello
>     [Bye], Bye

violating the immutability contract of `Sequential`.

In theory, this could be fixed by making `iterator` and `findLast` non-`default` only. However, I think we should also consider making `Singleton` `final` (possibly `ArraySequence` as well, though that’s already `sealed`).

**Comment by gavinking** [comment]
Done.

**Comment by lucaswerkmeister** [comment]
`ArraySequence` is intentionally not `final`?

**Comment by gavinking** [comment]
Does it matter? Well, it's `sealed`, which is basically as good as if it were.

**Comment by lucaswerkmeister** [comment]
Probably doesn’t matter, no.

**Comment by gavinking** [comment]
@74e571a4e6d75dfe6f9da67cb31323d715ef8095

**Comment by lucaswerkmeister** [comment]
Alright, thanks :)
