### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#648]
That's rather handy in OpenShift

**Comment by quintesse** [comment]
Probably best in `process`, right? (it seems at least environments are associated with processes)

**Comment by quintesse** [comment]
Btw, I just saw there's also no way to get the list of properties.

The API for these things in Java are strangely different even though they're both basically `Map<String, String>`, but Java's `System.getenv()` returns a `Map` while `System.getProperties()` returns a `Properties` object.

But given the fact we don't have an implementation of `Map` in the language module and also seeing that `ceylon.process::createProcess()` takes an argument of type `<String->String>[] environment` we could add attributes like `propertyValues` and `environmentValues` returning `<String->String>[]`.

**Comment by FroMage** [comment]
Oh yeah, a `<String->String>[]` value which is not a `Map` is _really_ useful NOT :(

**Comment by quintesse** [comment]
Yeah, don't blame me :/

**Comment by gavinking** [comment]
Done.

**Comment by quintesse** [comment]
And no way to get the entire list?
