### ISSUE TITLE
Cannot use `suppressWarnings` annotation on module.

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#649]
It does not appear to be allowed, is there a reason why?

**Comment by FroMage** [comment]
Especially for the `reservedNamespace` one it would help.

**Comment by gavinking** [comment]
Fixed. An oversight, I presume.

**Comment by FroMage** [comment]
Thanks, I hope the typechecker supports it now ;)

**Comment by gavinking** [comment]
It always did.

**Comment by FroMage** [comment]
That's only if you include "should work but there are no tests" as "supports it" ;) There can't have been tests because it was not allowed until this fix.

**Comment by gavinking** [comment]
There is *no difference* between a module descriptor node and any other
node type.

On Mon, Apr 13, 2015 at 4:57 PM, Stéphane Épardaud <notifications@github.com
> wrote:

> That's only if you include "should work but there are no tests" as
> "supports it" ;) There can't have been tests because it was not allowed
> until this fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon.language/issues/649#issuecomment-92389789>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org

**Comment by FroMage** [comment]
Well, I assume that disabling warnings on a module disables warnings for the whole module, no?

**Comment by FroMage** [comment]
Or just the warnings on the module declaration? Still this is not tested ATM.

**Comment by FroMage** [comment]
Actually no, I don't know what behaviour I'd assume TBH.

**Comment by tombentley** [comment]
I always assumed just the module descriptor.

**Comment by FroMage** [comment]
That seems a reasonable behaviour, provided the same is true of other locations (package).

**Comment by gavinking** [comment]
Just on the module descriptor _of course_!
