### ISSUE TITLE
Testing assignability to type argument Object fails

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.language#653]
```ceylon
Boolean f<T>(Anything a) => a is T;
shared void run() => print(f<Object>(""));
```
prints `false`. This only appears to happen for the type argument `Object`.

Filing this issue in ceylon.language because the [generated code](https://gist.github.com/lucaswerkmeister/a2004e381485d6984ed6) seems to be correct.

**Comment by lucaswerkmeister** [comment]
Note that this is a fairly recent breakage, as it worked yesterday (to be precise, self-built IDE version `Ceylon IDE	1.1.1.v20150409-1613-Final` couldn’t reproduce this bug).

**Comment by lucaswerkmeister** [comment]
Perhaps due to @gavinking’s optimizations in f547210f941f6b0e705b1d0b023ef28be0794f99 and 53d884b54345aaf5a0b1ee6f5d47c1e6c8c817d5?

**Comment by gavinking** [comment]
@lucaswerkmeister should be fixed, thanks.

**Comment by lucaswerkmeister** [comment]
Yup, thanks!
