### ISSUE TITLE
is on Tuple.getRest() is wrong

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#655]
I assume this is a bug in `Tuple.$getType$()`:

    Object x = [1,*('a':26)].rest;
    print(x is Tuple<Anything,Anything,Sequential<Anything>>);//prints true

A `Measure` is not a `Tuple`.

**Comment by gavinking** [comment]
> I assume this is a bug in `Tuple.$getType$()`:

I assume not, since you're not applying `is` to the tuple! You're applying it to the tail of the tuple, which is a measure, so why would `Tuple.$getType$()` be called?

**Comment by tombentley** [comment]
Ah, true. Well there's a bug in there *some*where. (Changed title).

**Comment by tombentley** [comment]
This looks to be a compiler bug :-(
