### ISSUE TITLE
ObjectArray.ObjectArrayIterable<T> should be non-public or @Ignored

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#659]
Currently the typechecker lets me call `ObjectArray.ObjectArrayIterable` from Ceylon code, resulting in a backend error `package java.lang.ObjectArray does not exist`.

So the inner class should be either `private` or `@Ignored`, but I'm not certain which. @tombentley? @FroMage?

**Comment by gavinking** [comment]
Fixed.

**Comment by FroMage** [comment]
I think it should better be private because you still can see the type or the iterable at runtime.

**Comment by gavinking** [comment]
@FroMage it is used from some places in the runtime.

**Comment by FroMage** [comment]
What is?

**Comment by gavinking** [comment]
`ObjectArray`. That's why it can't be `private`. FTR, it's your very own code in the metamodel that uses it :-)

**Comment by FroMage** [comment]
What, and you expect my code to work since when? Your lack of making sense is disturbing.

What happens when you get an instance of this iterable and call `type()` on it? What happens when you call `is Iterable<...>` on it? If it works then fine, if not we have a problem.

**Comment by gavinking** [comment]
> What happens when you get an instance of this iterable and call `type()` on it?

A really unhelpful error:

```
Exception in thread "main" com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unsupported declaration type: UnknownType
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1724)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1719)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:851)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorsForProducedTypes(Metamodel.java:888)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeDescriptorForProducedType(Metamodel.java:799)
```

> What happens when you call `is Iterable<...>` on it?

If I do `objectArray.iterable is {Object*}` evaluates to `true`, when it should evaluate to `false`, because of a bug I reported months and months ago.

So then this is your guys problem. If `private` doesn't work and `@Ignore` doesn't work, I'm not sure what I'm supposed to do about this. Is there some other way to hide it? I can't think of one.

**Comment by FroMage** [comment]
Why would `private` not work?

**Comment by gavinking** [comment]
I just explained: because _you_ use `ObjectArrayIterable` in your implementation of the metamodel!

**Comment by FroMage** [comment]
AFAICT we can only access `ObjectArray` as a special case from `java.lang`, so if we turn the `ObjectArrayIterable` into a toplevel class it won't be visible anymore. Perhaps that'd work?

**Comment by gavinking** [comment]
Sounds good to me.

**Comment by FroMage** [comment]
In theory, fixed and all tests pass, but I didn't find how to test this. Reopen if it's not fixed.
