### ISSUE TITLE
ObjectArray<Nothing>, ObjectArray<X|Y>

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#660]
This:

```ceylon
ObjectArray<Body> bodies
        = ObjectArray(5);
```

And this:

```ceylon
interface K {}
interface I satisfies K {}
interface J satisfies K {}
ObjectArray<K> ks
        = ObjectArray<I|J>(5);
```

Both fail at runtime with a CCE.

    java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lceylon.language.Integer;

What should we do about this? There's certainly no _elegant_ fix.

**Comment by gavinking** [comment]
Possible fixes:

1. Make it a runtime error to instantiate an `ObjectArray` with a union/intersection/nothing element type.
2. Special-case `ObjectArray` in the _typechecker_, and make it a compile-time error.

I lean toward 2.

**Comment by gavinking** [comment]
Of course we can't do 2 'cos type parameters. So I guess if we're going to make it an error, it has to be a runtime error. Looks like `com.redhat.ceylon.compiler.java.Util.makeArray()` is the right place to do this.

**Comment by gavinking** [comment]
I initially rejected this idea, but an alternative solution is to make `ObjectArray` invariant in its type parameter. That might be the more correct solution, but I need to think it through properly.

**Comment by gavinking** [comment]
Making it invariant would not quite be enough. I would also have to outlaw the use of use-site variance for `ObjectArray`.

**Comment by gavinking** [comment]
Ah so we tried to go down the invariant path once before in https://github.com/ceylon/ceylon-compiler/issues/1753, and there is a good discussion there of why it can't work.

So I'm back to the choice of two bad options:

1. making it a runtime exception to instantiate e.g. `ObjectArray<X|Y>`, or
2. leaving it just the way it is now.

It's not clear which is less worse.

**Comment by jvasileff** [comment]
Disallow creating an `ObjectArray<TypeParam>` in the typechecker, too? (like Java)

**Comment by gavinking** [comment]
@jvasileff well, yeah, sure, that would work, but that's a really much harder restriction than we need.

Remember, that because we have reified generics, we don't need any such restriction. We really do legitimately create a Java `Integer[]` array when we instantiate `ObjectArray<T>` and `T==Integer` at runtime.

**Comment by gavinking** [comment]
I have added a runtime restriction on the kinds of element types allowed for `ObjectArray`.

Does anyone disagree with this resolution?

**Comment by jvasileff** [comment]
I think it's a bit odd to have to document extra restrictions on type parameters that aren't enforced by the type checker. But I guess it doesn't matter anyway since I think `ObjectArray` should only be used when necessary for interop.

**Comment by gavinking** [comment]
@jvasileff No question, it's certainly odd. But I mean that's why we have our whole `Array` abstraction: to unodify arrays. `ObjectArray` is there _only_ really for interop.
