### ISSUE TITLE
problem reading SeeAnnotation of anonymous class on JS

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#661]
Given:

    class SomeClass() {}
    see( `class SomeClass` )
    object someObject extends SomeClass() {}

This:

    print( `value someObject`.annotations<SeeAnnotation>() );

prints `[ceylon.language::SeeAnnotation@2]`. But this:

    print(`class someObject`.objectValue?.annotations<SeeAnnotation>());

prints `[]`.

Was https://github.com/ceylon/ceylon-spec/issues/1232.

**Comment by chochos** [comment]
I tried to run this on JVM for comparison and got this error at runtime:

Exception in thread "main" com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: While reflectively instantiating class ceylon.language.SeeAnnotation on element value someObject

**Comment by chochos** [comment]
BTW I defined SomeClass and someObject as toplevel

**Comment by gavinking** [comment]
Maybe make SomeClass shared. But that's interesting.

**Comment by chochos** [comment]
Still fails, even with both the class and the object shared.

**Comment by gavinking** [comment]
@chochos I can't reproduce that. The code above runs perfectly for me on the JVM.

**Comment by chochos** [comment]
Still fails for me on JVM. Perhaps it runs on IDE but fails on CLI.

**Comment by gavinking** [comment]
Well then you and @FroMage need to sort this stuff out between the two of you. I have done what I can and the code worked perfectly for me in the IDE.

**Comment by FroMage** [comment]
@chochos if something fails for the JVM open an issue and I'll fix it.

**Comment by gavinking** [comment]
But please don't clog up the c.l issue tracker with issues not really affecting c.l because apparently nobody except me ever looks at the list of open issues there, so stuff just rots.

**Comment by FroMage** [comment]
well, that's where we put metamodel bugs.

**Comment by FroMage** [comment]
and I do fix them, as soon as the issue count on ceylon-compiler is zero, which doesn't happen often

**Comment by gavinking** [comment]
A big that only affects CLI is not a metamodel bug.

**Comment by FroMage** [comment]
Ah, how I long for the OBR… I don't care where it's open as long as we can fix it.

**Comment by gavinking** [comment]
Thanks :)
