### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#665]
Due to characters:

```
**** ASSERTION FAILED "888.character is an invalid Unicode codepoint" ****
**** ASSERTION FAILED "55210.character is an invalid Unicode codepoint" ****
**** ASSERTION FAILED "98537.character is an invalid Unicode codepoint" ****
**** ASSERTION FAILED "1114111.character is an invalid Unicode codepoint" ****
**** ASSERTION FAILED "-1 is not a valid unicode codepoint" ****
**** ASSERTION FAILED "1114112 is not a valid unicode codepoint" ****
```

**Comment by gavinking** [comment]
Disable those tests.

**Comment by FroMage** [comment]
Are they supposed to become enabled in the future? Should I remove or comment them out? What's the issue tracking this?

**Comment by gavinking** [comment]
You can remove them of you like.

**Comment by FroMage** [comment]
I don't get it, what were those tests testing? Every invalid code point?

**Comment by gavinking** [comment]
Dude there was a whole discussion of this last week that you ignored.

We used to pretend to prevent you creating a Character for an unassigned code point. We stopped pretending.

**Comment by FroMage** [comment]
I'm not questioning the logic for the change. I'm questioning the test. It looks like a random subset of invalid code points. I'm also questioning you running the tests before pushing code ;)

**Comment by FroMage** [comment]
And I did not ignore it, I was against that change and did reply.

**Comment by FroMage** [comment]
Apparently _you_ did the ignoring of my opinion ;)

**Comment by gavinking** [comment]
I have not been able to run c.l tests for a while.

**Comment by gavinking** [comment]
Aw Stef I would never ignore your opinion! I always treat your opinion with the respect it deserves ;)

**Comment by FroMage** [comment]
I'm not complaining that you ignore it, I'm used to that, I'm merely opposed to you pretending I did not participate.

**Comment by gavinking** [comment]
Apparently this is fixed.
