### ISSUE TITLE
refined Object.string never seen as mutable by metamodel on JVM

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#670]
On the JVM only, it is not possible to mutate a `string` attribute, even when marked `variable`. I was able to work with mutable attributes refined from my own classes and interfaces, so I'm not sure whether or not this issue is strictly limited to `Object.string`.

```ceylon
class FooString() {
    shared actual variable String string = "x";
}

shared
void meta() {

    value fooString = FooString();
    fooString.string = "y"; // ok, of course

    `FooString`.getAttribute<FooString,String,String>("string")
            ?.bind(fooString)
            ?.set("updated1"); //error
    //ceylon run: Incompatible type: actual type of applied declaration is
    //Attribute<FooString,String,Nothing> is not compatible with expected type:
    //Attribute<FooString,String,String>. Try passing the type argument explicitly
    //with: memberApply<FooString,String,Nothing>()

    `FooString`.getAttribute<FooString>("string")
            ?.bind(fooString)
            ?.setIfAssignable("updated2"); // error    
    //ceylon run: Value is not mutable
    //ceylon.language.meta.model.MutationException "Value is not mutable"

    print(`FooString`.getAttribute<FooString>("string")
                ?.declaration?.variable); // ** false **

    print(`FooString`.getAttribute<FooString>("string")
                ?.declaration?.setter); // ** <null> **
}
```

**Comment by gavinking** [comment]
This is probably specific to `Object.string`, because of the special-case mapping to `toString()`.

**Comment by gavinking** [comment]
P.S. I'm guessing the bug here is actually in the compiler, not in `ceylon.language`.

**Comment by FroMage** [comment]
So after a bit of digging through git history, this is due to https://github.com/ceylon/ceylon-compiler/issues/432, but I think it needs fixing since it affects not just interop but also Ceylon code.

**Comment by FroMage** [comment]
I changed the previous rules to properly handle `string` and `hash` setters when there is no getter.
