### ISSUE TITLE
Type inference does not work with function using multiple parameters lists

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon.language#673]
The following code does not compile:

```ceylon
shared Item theItem<Item>(String name)(Item item) => item;

void run() {
    value x = theItem("")(1); // ERROR on the 1
}
```

Because of error:

```
Argument must be assignable to parameter type: Integer is not assignable to Nothing
```

Explicitly giving the type to the function fixes the problem.

```ceylon
value x = theItem<Integer>("")(1); // OK
```

However, this should work because when the function has only one parameter list, the explicit type declaration is not required:

```ceylon
shared Item theItem<Item>(Item item) => item;

void run() {
    value x = theItem(1); // OK!
}
```

**Comment by gavinking** [comment]
Well, in fact this is correct according to the spec. The second argument list is considered the argument list of an _indirect invocation_, and so therefore it does not play a part in type argument inference.

Could we change that? Well, yes, sure, in principle, though I have not recently evaluated that to see exactly how hard it would be to implement. Is there a compelling _reason_ to change it? Well, I haven't run into one _yet_...

**Comment by renatoathaydes** [comment]
I was writing a library that create parsers, and each parser requires a name.

```ceylon
value parser = string("my parser name")("someString");
```
I had to change from this because of this problem, as when combining parsers, I would have to provide the parameter type to each function (and the error messages made it almost impossible to know which ones were wrong). For example;

```ceylon
value ceylonParser = parserChain(
    either("modifier")(string()("shared"), string()("actual")),
    parserChain("return type")(capitalLetter(), many()(either(letter(), char('_'))))
);
```

Would become:

```ceylon
value parser = parserChain<Character[]>(
    either<Character[]>("modifier")(string<Character[]>()("shared"), string<Character[]>()("actual")),
    parserChain<Character[]>("return type")(capitalLetter(), many<Character[]>()(either<Character[]>(letter(), char('_'))))
);
```

It becomes so ugly that it is impossible to use. I had to change the design to take only one parameter list, but then I could not use variadic parameters because the name parameter needs to have a default value, but not the other argument (ie. I had to make the other argument an Iterable instead of using variadic arg, and completely against my design decision to use the same pattern as Haskell's `Parsec`, I had to make the name argument the last one, not the first).

Another solution that could have helped me would have been the possibility of having variadic arguments or defaulted parameters in the second list of arguments of a function.

As it currently stands, my original design had to be completely sacrificed due to these language limitations :(

**Comment by gavinking** [comment]
@renatoathaydes looks like #810 would help. That's one we already *do* intend to fix.

**Comment by gavinking** [comment]
P.S. @renatoathaydes this issue is mis-filed. It should have been filed against `ceylon-spec`, not the language module.

**Comment by renatoathaydes** [comment]
Moved to https://github.com/ceylon/ceylon-spec/issues/1292
