### ISSUE TITLE
Add ReferenceDeclaration

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#681]
This is similar to #680. If we add:

```ceylon
shared sealed interface ReferenceDeclaration
        satisfies ValueDeclaration {}
```

Then we can constrain Java annotations like `@Inject` and `@Column` to apply only to `FunctionDeclaration|ReferenceDeclaration`, thus resolving the ambiguities in that.

**Comment by gavinking** [comment]
The Java and typechecker side of this is now done. @chochos I'll let you close this when you've finished with the JS side.

**Comment by chochos** [comment]
it would be nice to have at least one example of where this thing is expected, to add some tests and make sure the behavior is the same on both backends

**Comment by jvasileff** [comment]
I'm still trying to understand this. A few questions:

* Is the idea that is should be impossible to apply a `FIELD` annotation to a `shared` attribute?
* To apply a `METHOD` annotation (constrained to `FunctionDeclaration`) to an attribute (`ValueDeclaration`?), you would continue to use `anno__GETTER` or `anno_SETTER`?
* Should `late String myString;` accept `ReferenceDeclaration` annotations, despite being guarded/accessed by get/set methods (it's currently allowed)?

Also, is it a bug that `functionOrReferenceAnnotation` is allowed for `something`?

```ceylon
final annotation
class FunctionOrReferenceAnnotation() satisfies
    OptionalAnnotation<FunctionOrReferenceAnnotation, FunctionDeclaration|ReferenceDeclaration> {
}

annotation
FunctionOrReferenceAnnotation functionOrReferenceAnnotation() =>  FunctionOrReferenceAnnotation();

class TestClass() {
    functionOrReferenceAnnotation
    shared String something = "";
}
```

**Comment by FroMage** [comment]
@gavinking can you restate your spec here from what you said on gitter?

**Comment by gavinking** [comment]
@chochos this is still not working on JS:

```ceylon
String name = "Gavin";
Object referenceDeclaration = `value name`;
print (referenceDeclaration is ReferenceDeclaration);
```

prints `false`.

**Comment by chochos** [comment]
should all metamodel refs to values be `ReferenceDeclaration`s? Or what's the difference?

**Comment by gavinking** [comment]
@chochos §4.8.1 of the spec defines what a "reference" is.

**Comment by gavinking** [comment]
Or, just call `Unit.getValueDeclarationType()`.

**Comment by jvasileff** [comment]
Didn't we determine on gitter that this method of disambiguation for Java interop won't work? This conversation is way too spread out over time...

**Comment by chochos** [comment]
this is working now on JS.

**Comment by FroMage** [comment]
@tombentley is this done on the JVM?

**Comment by FroMage** [comment]
@chochos this is FAR from done on JS. I see PLENTY of direct calls to `OpenValue$jsint()` in the metamodel native JS code that should be conditional to sometimes return `OpenReference$jsint()`. Also in the generated JS code.

**Comment by FroMage** [comment]
AND what's worse: there doesn't seem to be any tests for this that would show this hasn't been implemented.

**Comment by tombentley** [comment]
I've added some tests. They're passing on JVM.

**Comment by FroMage** [comment]
Thanks, we also need to test `members<ReferenceDeclaration>` and friends that filter on member type.

**Comment by tombentley** [comment]
Oh yeah. Those. OK I'll add more tests...

**Comment by FroMage** [comment]
OK, now on to @chochos to make sure this all gets supported.

**Comment by FroMage** [comment]
@chochos is this done then? Looks like the tests are passing, I'll call this done.

**Comment by FroMage** [comment]
Damnit, no, it does not pass the tests:

```
[ceylon-run-js] ceylon.language::AssertionError "Assertion failed: 'members .size == 3' at runtime.ceylon (1557:10-1557:29)"
[ceylon-run-js]     at AssertionError (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:4932:1)
[ceylon-run-js]     at Object.asrt$ (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:263:25)
[ceylon-run-js]     at checkClassMembers (/home/stephane/src/java-eclipse/ceylon.language/build/test/metamodel/0.1/metamodel-0.1.js:7695:5)
[ceylon-run-js]     at run (/home/stephane/src/java-eclipse/ceylon.language/build/test/metamodel/0.1/metamodel-0.1.js:8494:1)
[ceylon-run-js]     at [eval]:1:285
[ceylon-run-js]     at Object.<anonymous> ([eval]-wrapper:6:22)
[ceylon-run-js]     at Module._compile (module.js:456:26)
[ceylon-run-js]     at evalScript (node.js:532:25)
[ceylon-run-js] ceylon.language.jsint::AppliedMemberClassCallableConstructor<metamodel::Constructors<ceylon.language::String>,metamodel::Constructors.Member,[]>
```

**Comment by chochos** [comment]
that one is not directly related to this, but I think @tombentley added it along with the tests for ReferenceDeclaration, for good measure.

**Comment by FroMage** [comment]
Done.
