### ISSUE TITLE
Type inference bug

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon.language#683]
In the following code, the wrong type is inferred in the last call, and this does not compile:

```ceylon
class X<out Y>(shared Y y) {}
X<To> transform<From, To>(X<From> x, To(From) convert)
        => X(convert(x.y));

X<String> x1 = X("10");
X<Integer?> x2 = transform(x1, parseInteger); // Error
```

The error is on `parseInteger`:

```
Argument must be assignable to parameter convert of transform: Integer?(String, Integer=) is not assignable to Integer?(String|Integer)
```

But there is no way that `From` could be an `Integer` in the above code.

If the type parameters are explicitly given, it compiles:

```ceylon
X<Integer?> x2 = transform<String, Integer?>(x1, parseInteger); // OK
```

**Comment by gavinking** [comment]
Renato this belongs in ceylon-spec. It isn't a problem with the language module.

**Comment by renatoathaydes** [comment]
Oh again... I thought that the type inference algorithm was implemented in ceylon.language.

Will move it.

**Comment by gavinking** [comment]
No. Type inference is part of the compiler. The typechecker to be exact.
