### ISSUE TITLE
incorrect and inconsistent `ValueDeclaration.setter` on JVM & JS

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#689]
The docs for `ValueDeclaration.setter` state:

> For modelling purposes variable reference values have a SetterDeclaration even though there is no such setter explicit in the source code.

So I would expect output of `false false true true` for:

```ceylon
shared class Model() {
    shared String constantProperty = "";
    shared String computedProperty => "";

    shared variable String variableProperty = "";
    shared String assignableComputedProperty => "";
    assign assignableComputedProperty {}
}

shared void testAssignability() {
    print(`Model.constantProperty`.declaration.setter exists);
    print(`Model.computedProperty`.declaration.setter exists);

    print(`Model.variableProperty`.declaration.setter exists);
    print(`Model.assignableComputedProperty`.declaration.setter exists);    
}
```

Instead, on the JVM, I get:
```
false
false
false
true
```
and for JS:
```
true
true
true
true
```

**Comment by FroMage** [comment]
@tombentley any memory of this?

**Comment by tombentley** [comment]
No memory, I'm afraid. I think the JS output is definitely wrong and need fixing.

IIRC we now have `ReferenceDeclaration`, which means the metamodels of references are now more distinguishable from those of getters/setters. I guess we should stick to the model though, and set the setter should exist for a `variable` reference.

**Comment by FroMage** [comment]
In fact, the docs are wrong and there's no setter unless the declaration (typechecker model, also respected by model loader) really has a setter (must be `variable` _and_ `transient`). So I will fix the docs and let @chochos fix the JS.

**Comment by FroMage** [comment]
Fixed it, and my first metamodel fix for JS :)

**Comment by chochos** [comment]
I'm so glad two human beings on this Earth have worked on that thing now.
