### ISSUE TITLE
ClassOrInterface.getAttribute api docs

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#691]
[`getAttribute`](http://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/meta/model/ClassOrInterface.type.html#getAttribute), which is:

```ceylon
shared formal Attribute<Container,Get,Set>? getAttribute<Container = Nothing, Get = Anything, Set = Nothing>(String name)
```
is supposed to throw
> `IncompatibleTypeException` If the specified `Container`, `Get` or `Set` type arguments are not compatible with the actual result.

But, `Container` actually works as a filter. Therefore, it will never be incompatible with the result.

```ceylon
print(`Integer`.getAttribute<Nothing ,Boolean,Nothing>("unit")); // ceylon.language::Integer.unit
print(`Integer`.getAttribute<Anything,Boolean,Anything>("unit")); // <null> (filtered by Container)
print(`Integer`.getAttribute<Nothing ,Boolean,Anything>("unit")); // throws due to Set type
```

So the docs seem unclear about how `Container` actually works. But I'm also wondering, would it make sense to just treat all type parameters as filters, and return null instead of throwing?

**Comment by FroMage** [comment]
This is a question for @gavinking.

**Comment by gavinking** [comment]
It seems to me that it would be better if it's a filter.

**Comment by FroMage** [comment]
OK, so a few comments:

- Changing this filtering to all type params would change a LOT of methods, so I suggest doing this in 1.3
- The fact that it returns `null` for `Anything` is actually not really filtering but just failing to find the attribute in that type.
- The fact that it returns `null` for `Nothing` is valid wrt. contravariance rules.
- The fact that it does not throw if you use a distinct container type such as `String` is actually a bug. 

I propose to fix this bug, tweak the docs to describe the container behaviour, and open a new issue for 1.3 if we want to do change this behaviour.

But IMO, filtering works well when you don't know the name, like `getAttributes()` where it makes sense to filter on types. I don't quite see why we should filter on type when we ask for a specific member whom we know by name. To me that should be an error. If you ask for `Integer.hash` and pretend it's a `String` that's just wrong. In fact, the typechecker will refuse ``Attribute<Integer,String> hash = `Integer.hash`;`` and produce an error, so I sort-of expect the same error at runtime for `` `Integer`.getAttribute<Integer,String>("hash");``

**Comment by jvasileff** [comment]
I'm not certain I agree about the filtering, but let me put more thought into a possible response.

For now, I'm wondering, **if** you are required to guess `Get` and `Set` correctly to avoid an exception, perhaps they should be removed, and `assert` should be required instead for narrowing?

**Comment by tombentley** [comment]
>  I don't quite see why we should filter on type when we ask for a specific member whom we know by name. To me that should be an error. If you ask for Integer.hash and pretend it's a String that's just wrong. 

The thing is you have an API which already handle "errors" by way of the optional return type. (Really there's not a big difference between the thing not having an attribute of the given name and the thing having an attribute with that name, but with the wrong type). So having the optional return type *and* the possibility of throwing just makes the API more painful for the client to use, as they end up doubling up their logic for dealing with alternative execution flows.

**Comment by FroMage** [comment]
> if you are required to guess Get and Set correctly to avoid an exception, perhaps they should be removed, and assert should be required instead for narrowing?

I think the idea was that it would lead to easier usage with the assertion done for you,

**Comment by FroMage** [comment]
> So having the optional return type and the possibility of throwing just makes the API more painful for the client to use, as they end up doubling up their logic for dealing with alternative execution flows.

Well, `null` is a success return value for "does this element exist with this name?". Where an exception means "you just gave us invalid arguments".

**Comment by FroMage** [comment]
So in fact, `` `Integer`.getAttribute<String>("x")`` is specified such that for disjoint container types, we look up the member in the common supertype, so it's right not to throw there as that's just a valid container type (`Object` in this case).

I clarified the docs, left the current behaviour for `getXX` but changed it to throw for `getDeclaredXX` if the container type is not a subtype, because _here_ that's wrong, and it did catch a few errors in the tests where we were passing inferred type arguments (`Anything` as container in this case) rather than default type arguments, so it did catch errors.

Again, just because I disagree with changing every type param to filter doesn't mean I oppose that change if enough people agree to it. I just think it can wait for 1.3 as that's a lot more work.

**Comment by FroMage** [comment]
@chochos changes in branch `691` need you to update the JS metamodel, so I won't merge it or close this issue until you're done.

Meanwhile, guys, feel free to open an issue for the changes you want for 1.3.

**Comment by chochos** [comment]
ok you can merge this now if you want

**Comment by FroMage** [comment]
Oh great I have a conflict with a reformatting commit :(

**Comment by FroMage** [comment]
OK merged.
