### ISSUE TITLE
flatten is broken in both backends

### ISSUE THREAD

**Issue by chochos** [ceylon/ceylon.language#699]
After trying to fix 100 bugs @jvasileff has filed for JS, I decided to rewrite the shameful mess that is `flatten` in JS. So I wrote some tests, to make sure the function does what it's supposed to do. Thing is, these tests break at runtime on JVM as well.

@gavinking please check that these tests I'm adding make sense; I wrote them according to the `flatten` documentation, to cover the 5 cases mentioned there.

**Comment by gavinking** [comment]
@chochos yes, those tests look right to me.

**Comment by chochos** [comment]
OK this is done in JS.

**Comment by jvasileff** [comment]
@chochos, is all of this pushed? I have a couple errors that started on the 29th, but wanted to avoid trying to distill them down to something reasonable if there are unresolved known issues or if this is a WIP.

Possibly not helpful at all, but with `compose(unit<B>, apply)`, I have:
```
[ceylon-test-js] ceylon.test::AssertionComparisonError "assertion failed: expected <[2, 4, 6, 8, 10]> but was <[[2], [4], [6], [8], [10]]>"
[ceylon-test-js]     at ceylon.language::AssertionError (ceylon/test/core/DefaultTestExecutor.ceylon 189:12-189:19)
[ceylon-test-js]     at ceylon.test::AssertionComparisonError
[ceylon-test-js]     at ceylon.test::assertEquals
[ceylon-test-js]     at test.com.vasileff.fc.core::wrapperExample
[ceylon-test-js]     at ceylon.language.jsint::apply
[ceylon-test-js]     at ceylon.language.meta.declaration::invoke
[ceylon-test-js]     at ceylon.test.core::invokeFunction$vvhr5f
[ceylon-test-js]     at ceylon.test.core::execute
[ceylon-test-js]     at ceylon.test.core::run
[ceylon-test-js]     at com.redhat.ceylon.testjs::run
```
and with `uncurry(Whole.minus)`:
```
[ceylon-test-js] ceylon.language::NativeError "TypeError: Cannot read property 'sign' of null"
[ceylon-test-js]     at ceylon.language::Throwable (ceylon/test/core/DefaultTestExecutor.ceylon 189:12-189:19)
[ceylon-test-js]     at ceylon.test.core::execute
[ceylon-test-js]     at ceylon.test.core::run
[ceylon-test-js]     at com.redhat.ceylon.testjs::run
```

**Comment by chochos** [comment]
there are a whole bunch of errors in JS but they're not because of `flatten` directly, it's related to spread-arg calls.

**Comment by jvasileff** [comment]
Ok, thanks, I'll set those aside for a while

**Comment by chochos** [comment]
`Whole` is from `ceylon.math` IIRC which is JVM-only I think

**Comment by chochos** [comment]
Can you please test again? I can't reproduce because I don't know where `unit<B>` or `apply` come from.

**Comment by jvasileff** [comment]
Thanks @chochos. The `uncurry(Whole.minus)` code works now (this is with my xmath module).

The other one still fails, so I'll try to reduce it to something you can test. For now, the best I can say is that the second of these *does* still work:

```ceylon
        =>  bind(source, compose(unit<B>, apply));
        =>  bind(source, (A a) => unit(apply(a)));
```
This is in higher-order generic code too, so maybe that has something to do with it. But it used to work.

**Comment by jvasileff** [comment]
@chochos, I got it! Shortest repro in a while:

```ceylon
String(Object) f = compose(identity<String>, Object.string);
print(f(5));
// Prints "[5]" instead of "5"
```

**Comment by FroMage** [comment]
I fixed this for the JVM, the test passes (not @jvasileff's latest bug: the original bug).

**Comment by FroMage** [comment]
So is this fixed or not then?

**Comment by chochos** [comment]
The original tests pass in JS as well but not the latest bug

**Comment by FroMage** [comment]
OK. Looks like it passes on the JVM :) Muahahaha.
