### ISSUE TITLE
preserve sign when Float.wholePart returns zero

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#700]
For `(-0.5).wholePart;`, both backends return `0.0` rather than `-0.0`.

I can create a patch for the Java side if you agree that `-0.0` is correct.

**Comment by gavinking** [comment]
I agree.

**Comment by tombentley** [comment]
@jvasileff's PR fixed this, I believe.

**Comment by jvasileff** [comment]
@tombentley, I haven't re-tested, but I believe this issue still exists on JS.

**Comment by tombentley** [comment]
Ah, sorry, let me reopen then.

**Comment by FroMage** [comment]
I guess I may be able to do the JS for this one.

**Comment by chochos** [comment]
Well then `runtime-js/numbers.js` look for `wholePart` and I think all you have to do is set `fmz$` flag on the returned value (in case it's 0 and the original value was less than zero, etc)

**Comment by FroMage** [comment]
Yay, fixed!
