### ISSUE TITLE
Type.subtypeOf() on member types is too stingy on JVM

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#711]
`subtypeOf` incorrectly returns `false` in some cases when member interfaces are inherited multiple times.

```ceylon
import ceylon.language.meta { type }

shared void run() {
    interface InterfaceA<out T> {}
    interface InterfaceAInteger satisfies InterfaceA<Integer> {}
    interface InterfaceAFloat satisfies InterfaceA<Float> {}
    class TestClass() satisfies InterfaceAInteger & InterfaceAFloat {}

    print(`InterfaceAInteger & InterfaceAFloat`.subtypeOf(`InterfaceA<Anything>`)); // true, good
    print(`InterfaceAInteger & InterfaceAFloat`.subtypeOf(`InterfaceA<Nothing>`)); // false, should be true
    print(type(TestClass()).subtypeOf(`InterfaceA<Anything>`)); // false, should be true
    print(type(TestClass()).subtypeOf(`InterfaceA<Nothing>`)); // false, should be true
}
```
* On JS, `true` is returned for each test.
* On the JVM, if the types are moved outside of the `run` function, `true` is returned for each test.

**Comment by FroMage** [comment]
So those are related to the fact that we use pseudo containers for local declarations to represent the container function (`run` in this case) and `Type.getSupertype` in `ceylon-model` omits the qualifying pseudo container so the tests don't pass. Since that happens to be in `getPrincipalInstantiation` I think @gavinking will solve this a lot better than me.

**Comment by FroMage** [comment]
Appears to be in `ModelUtil.principalQualifyingType` where we have two pseudo-types as qualifying types but we return null because `td.getContainer()` is a `TypedDeclaration`.

**Comment by gavinking** [comment]
@FroMage does that [fix](ceylon/ceylon-model@6c022e2) look right to you?

**Comment by FroMage** [comment]
Looks right, does it work too?

**Comment by gavinking** [comment]
Well for the given tests yes,

**Comment by FroMage** [comment]
I confirm this test now passes.
