### ISSUE TITLE
Bad results for ClassOrInterface.equals & string w/use site variance

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#714]
`equals()` does not take use site variance into account:

```ceylon
print(`MutableList<out Object>` == `MutableList<Object>`);
// true (should be false)

print(`Array<out Object>` == `Array<Object>`);
// true (should be false)
```

likewise, `string` is less informative than it could be:
```ceylon
print(`Array<out Object>`);
// ceylon.language::Array<ceylon.language::Object>
// better would be:
// ceylon.language::Array<out ceylon.language::Object>
```

**Comment by FroMage** [comment]
Well, I don't think variance made its way into this API at all.

**Comment by FroMage** [comment]
@gavinking do I add it in the same form as the model with `shared Map<TypeParameter,Variance> varianceOverrides`?

**Comment by jvasileff** [comment]
> made its way into

In case it helps, I did find things like `Type.subtypeOf` to work on type literals w/variance annotations, so the annotations are acknowledged. But maybe it's just delegating to other code.

**Comment by gavinking** [comment]
@FroMage, that sounds OK to me, but it feels like even better would be this:

```ceylon
shared alias TypeArgument => [ClosedType<>,Variance];

"A generic model which has closed type arguments."
shared sealed interface Generic {
    "The map of type parameter declaration to type arguments for this generic model."
    shared formal Map<TypeParameter, TypeArgument> typeArguments;
    "The list of type arguments for this generic model."
    shared formal TypeArgument[] typeArgumentList;
}
```

**Comment by FroMage** [comment]
We can, but that's a breaking change.

**Comment by gavinking** [comment]
So give them new names, `typeArgumentsWithVariances` or whatever.

**Comment by FroMage** [comment]
Mmm, your version seems to imply that we'd get a variance even if there's no use-site variance annotation, which sort of implies that we'd have to get that variance from the declaration site, which does not let us differentiate between use-site-variance and no-use-site-variance.

**Comment by FroMage** [comment]
Sorry that was bullshit. It's about USE-SITE variance info, not declaration site. So `invariant` always means the absence of any use-site variance.

**Comment by FroMage** [comment]
This is all fixed in the `714` branch. I added tests as well. @chochos this is now for you to do for JS. I added all the required JS glue, only the code is missing.

**Comment by chochos** [comment]
Almost done...

**Comment by chochos** [comment]
Done. Should I merge this or do you want to do that @FroMage ?

**Comment by FroMage** [comment]
Depends on whether @tombentley wants us to wait before we merge.

**Comment by tombentley** [comment]
There's a failing test for this issue in the language suite. Does it need to be merged now?

**Comment by FroMage** [comment]
I suppose it can be merged now, no?

**Comment by chochos** [comment]
Ah yes I pushed that test then remembered we already had one on the branch. But the newer one on master is more thorough, although we should indeed merge both.

**Comment by FroMage** [comment]
OK, I merged with master and completed where we were missing things after the merge. I can run the JVM tests, but not the JS test since JS does not run at all for me (reported the issue).

I'll leave this open for @chochos to close after he's verified that all the JS tests for that pass.

**Comment by chochos** [comment]
did you pull before merging? It looks like my impl's are gone

**Comment by chochos** [comment]
I don't know WTF you did but what you merged was not the latest stuff. I'll have to bring my impl's from my branch

**Comment by FroMage** [comment]
Oh crap, perhaps I forgot. Damn. Really sorry :( were you able to get them back?

**Comment by chochos** [comment]
yes I managed to reintegrate all this stuff. use-site variance tests are passing.

**Comment by FroMage** [comment]
Pfew, cool.
