### ISSUE TITLE
make Callable.equals always return false

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#716]
I propose to make `Callable.equals` always return false, even when `===` (if it were allowed) would return true.

Relying on function equality is dubious, and it is not currently well defined. And if equality were well defined, supporting it could lead to lost optimization opportunities (having to check captures, or making sure to always use the *same* `Callable` instance for "equal" functions.)

A few examples, although I'm sure with some thought an even more compelling argument could be made:

```ceylon
    print(identity<String> == identity<Integer>);
    // false on jvm, true on js

    value single = Singleton("");
    print(single.each == single.each);
    // false on jvm, true on js

    print(String.clone == String.clone);
    // false on jvm, false on js
```

**Comment by FroMage** [comment]
So, if I get this right, that's a change for JS, right?

**Comment by jvasileff** [comment]
I think `equals()` would need to be refined on the JVM as well. And probably a small doc addition to `Callable`.

On JVM & JS:

```ceylon
shared void run() {
    value f = () => null;
    value g = () => null;
    print(f == f); // true
    print(f == g); // false
}
```

**Comment by FroMage** [comment]
OK.

**Comment by gavinking** [comment]
This would break the explicit contract of `Identifiable`.

**Comment by jvasileff** [comment]
`Callable`s aren't `Identifiable`, right?

**Comment by gavinking** [comment]
Ah, good point.

**Comment by FroMage** [comment]
I can make that change, but then it won't be consistent with `hash` anymore. We can't ask the same object to return a new hash value every time it's called. Would that be a problem?

**Comment by FroMage** [comment]
The alternative is to specify that `Callable.equals` has unspecified behaviour.

**Comment by lucaswerkmeister** [comment]
`hash` only mandates that

> if `x==y` then `x.hash==y.hash`.

This doesn’t mandate that unequal objects must have different hashes. You could just think of it as a hash collision :)

**Comment by FroMage** [comment]
Yes, true.

**Comment by FroMage** [comment]
Done for both JVM and JS.
