### ISSUE TITLE
process.return should have return type of Nothing

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon.language#720]
As stated. Right now the type checker's definite return checks break if a function exits rather than returning.

**Comment by lucaswerkmeister** [comment]
I agree that `process.exit` should return `Nothing`, but this wouldn’t actually affect definite return analysis until ceylon/ceylon-spec#1179 is added.

**Comment by gavinking** [comment]
Well you can write `return process.exit();`
