### ISSUE TITLE
`caseValues` does not work with closed enum of value constructors

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon.language#721]
This code
```ceylon
class Foo of bar|baz {
	shared new bar{}
	shared new baz{}
}
shared void run(){
	print(`Foo`.caseValues);
}
```
on the Java backend outputs `[]` and crashes the JS backend with `ReferenceError: $prop$getBar is not defined`

**Comment by tombentley** [comment]
Those cases are not types, but constructors. In general the `of` clause can now contain types and values, so I suppose the type of `caseValues` will need to change to reflect this. Somehow.

**Comment by gavinking** [comment]
@tombentley well, I dunno, they are _value_ constructors, and a value constructor is a value.

**Comment by tombentley** [comment]
Yes, but my point is that right now `caseValues` has type `Type[]`, and since a `Value` is not a `Type` that's got to change, right?

**Comment by tombentley** [comment]
An mentioned, currently `ClassOrInterface.caseValues` is a `Type[]`. (Note the inconsistency in name versus type: case*Values* but it returns types).

I can declare `ClassOrInterface.caseValues` to be `<Type|ValueConstructor>[]` (and refine it on `MemberClass` and `InterfaceModel` back to `Type[]` in an effort to minimise breakage).

Or maybe it would be better to leave caseValues alone and just add a `cases` attribute.

But I will also need a corresponding thing in `ClassDeclaration`. Right now it has `caseTypes` which is a `OpenType[]`. Note another inconsistency: It was `caseValues` in the model, but `caseTypes` in the declaration. There's not really an `Open*` for values, so making `caseTypes` a <OpenType|ValueConstructorDeclaration>[]` seems rather odd. I could add a `cases` attribute for this too.

The final question is whether the union should be `Type|ValueConstructor` or `Type|Value`, likewise `ValueConstructorDeclaration` or `ValueDeclaration`.

**Comment by tombentley** [comment]
Oh, btw this is all on the `ctor-models` branch.

**Comment by luolong** [comment]
Errm... excuse me my ignorance, but for a layman this whole discussion sounds like a lot of nitpicking.

Isn't the whole point of _value constructors_ that they construct values. In essence they are a different syntax offering a similar concept as top level `object` declarations.

Thereby, whenever there is a valueConstructor of some name, there should also be a corresponding value with the same name? no?

But then, maybe I am missing something...

**Comment by tombentley** [comment]
@luolong you're right that a value constructor is a value. 

The problem is that the metamodel already had an attribute called `caseValues` which returned the *type models* of the cases, rather than the value models. That was OK when the `of` clause could only include types (we got away with it for `object` declarations in the `of` clause because we chose arbitrarily to return the type model of the anonymous class, not its value model), but is not OK now it can include value constructors (which don't have their own type model). In short the API we have is rubbish and it's about how best to fix that.

**Comment by gavinking** [comment]
@tombentley shouldn't that be `Type[]|ValueConstructor[]`?

**Comment by tombentley** [comment]
Ah, yes I suppose it should, since we can't have a class with is enumerated with value constructors and subclasses. Thanks @gavinking.

**Comment by tombentley** [comment]
@FroMage, I'm trying to decide whether to break (in the name of fixing) the existing `ClassOrInterface.caseValues`, or to write a new `ClassOrInterface.cases`. 

    "The list of case values for this type. This omits any case type to 
     only contain case values."
    shared formal Type[] caseValues;

This means that the returned `Type[]` will contain only the types (i.e. `Class`) of anonymous classes, is that correct? In other words for

    abstract class Enumerated of Subcass|obj {}

It is supposed to return `` [`obj`] ``?

**Comment by gavinking** [comment]
I think you should break it. I think `caseValues` was always supposed to return a list of _instances_, not types.

**Comment by gavinking** [comment]
Wait wait wait. Are we all confused about what `Type` means in that code?

    shared sealed interface ClassOrInterface<out Type=Anything> { .. }

**Comment by gavinking** [comment]
`caseValues` returns a sequence of _instances of the class or interface_!

**Comment by tombentley** [comment]
I can't parse that.

**Comment by tombentley** [comment]
I'm proposing this:

    """The list of types and values, or value constructors that 
       this class or interface enumerates.
       
       Given
       
           abstract class Foobar() of Foo|bar {}
       
       then `` `Foobar`.cases`` would be a `Type|Value[]` 
       equal to ``[`Foo`,`bar`]``.
       
       And given
       
           class Baz of one|two {
               shared new one {}
               shared new two {}
           }
        
        then `` `Baz`.cases`` would be a `ValueConstructor[]`
        equal to ``[`Baz.one`,`Baz.two`]``
     """
    shared formal <Type|Value>[]|ValueConstructor[] cases;

**Comment by FroMage** [comment]
What he's saying is that `caseValues` already returns instances, not types. `Type` is not `ceylon.language.meta.model::Type` but the type argument to `ClassOrInterface<Type>`, which means that for `ClassOrInterface<Boolean>`, `caseValues` will be of type `Boolean[]`: the instance values of `true` and `false`. ATM at least.

**Comment by tombentley** [comment]
Right, makes sense now.

**Comment by FroMage** [comment]
So the function name wasn't lying after all ;) But yeah, I agree the type signature makes it confusing.

**Comment by tombentley** [comment]
Yes, who'd've thunk it, you weren't smoking crack after all.

I wonder though it we can think of a better name than `Type` for the type parameter of `Class`, because it really *is* confusing.

**Comment by FroMage** [comment]
I initially did not respond because I totally believed I was to blame ;)

**Comment by gavinking** [comment]
I remember this came up once before with me bitching that why the hell was something that returns types named "case values" and then Stef coming back to me and saying it was my fault 'cos I had suggested that name. The irony.

**Comment by tombentley** [comment]
Should the list include non-`shared` value constructors?

```
class ClosedEnumValueConstructors
    of alpha | beta {
    shared new alpha {}
    new beta {}
}
```

Should I even be able to enumerate a non-`shared` value constructor in the `of` clause @gavinking ?

**Comment by gavinking** [comment]
@tombentley ugh. Great question.

**Comment by gavinking** [comment]
Yes. It should. The visibility controls are a _compile time_ restriction, _not_ a runtime restriction.

**Comment by FroMage** [comment]
+1

**Comment by tombentley** [comment]
Well OK, but it would be the first time I can think of where a thing appears in a declaration, but the client cannot see that thing's declaration.

**Comment by FroMage** [comment]
He can using the metamodel anyways, no?

**Comment by gavinking** [comment]
> Well OK, but it would be the first time I can think of where a thing appears in a declaration, but the client cannot see that thing's declaration.

Well it's kinda the first time we have something that directly returns an _instance_.

**Comment by sgalles** [comment]
I'm not sure that's the same issue, but asking here just in case :

Now, I can get the instances of the closed enum, but via the metamodel, can I get the declaration name of the instances ?

That's to say, for this class
```ceylon
shared class Foo of aaa|bbb{
	shared new aaa{}
	shared new bbb{}
}
```
How can I used the metamodel to get the strings `aaa` and `bbb` ? (actually I'm trying to emulate http://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#name%28%29 )

**Comment by tombentley** [comment]
Well there's `` `class Foo`.constructorDeclarations()*.name`` I suppose, or `` `Foo`.getDeclaredValueConstructors()*.declaration*.name`` if you want to be sure to get only the value constructor instances.

**Comment by sgalles** [comment]
Ah, OK, thanks, that's interesting. 
It means that if I want to get the declaration name of the cases, the `caseValues` method is usefull for traditional enumerated instances.
```ceylon
abstract class Suit(String name)
		of hearts | diamonds | clubs | spades {}
// blablabla
print(`Suit`.caseValues.collect((v) => type(v).declaration.name));
``` 
But for a closed enum of value constructor I just use
``` 
`Foo`.getDeclaredValueConstructors()*.declaration*.name`
```
and actually skip the `caseValues` step
