### ISSUE TITLE
REQUIRED NATIVE FILE MISSING FOR ceylon.language::Array.ofSize => ../ceylon.language/runtime-js/Array/ofSize.js, containing ofSize

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#722]
That can't be right ;)

**Comment by chochos** [comment]
the file is called `OfSize.js` so you need to move it to `ofSize.js`. I can't do that because the stupid filesystem on my machine is case insensitive (but case preserving, so it's like case indifferent or something, really)

**Comment by FroMage** [comment]
Oh, brilliant.

**Comment by FroMage** [comment]
OK fine, I'll do that.

**Comment by FroMage** [comment]
But I suggest that in your stitcher you add some code which checks that the file it got has the exact same case as you asked for, and reports an error otherwise, this way next time you can catch the error yourself, on any case-insensitive FS.

**Comment by chochos** [comment]
fine. Please push the change while you're at it.

**Comment by FroMage** [comment]
Will do.

**Comment by FroMage** [comment]
Fixed.
