### ISSUE TITLE
memberInvoke incorrectly throws IncompatibleTypeException on JS

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#724]
Object a = 1;
    Object b = 2;
    print(`function Comparable.compare`.memberInvoke(a, [], b));

Works on JVM but on JS throws:

/home/dietmar/Software/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.0.v20141013-1416/repo/ceylon/language/1.1.0/ceylon.language-1.1.0.js:5498
if (a[i]!==undefined && !is$(a[i],val_t))throw IncompatibleTypeException$meta$
                                               ^
ceylon.language.meta.model::IncompatibleTypeException "Wrong type for argument 0, expected ceylon.language::Integer got ceylon.language::Integer"

**Comment by FroMage** [comment]
Originally reported by @dhoehmann at ceylon/ceylon-sdk#405

**Comment by chochos** [comment]
huh, I get `expected Number got Integer`
