### ISSUE TITLE
getDeclaredMethod not working on JS

### ISSUE THREAD

**Issue by dhoehmann** [ceylon/ceylon.language#725]
type(1.0).getDeclaredMethod&lt;Nothing, Anything, Nothing&gt;("plus");

returns &lt;null&gt; when executed on JS (works correctly on JVM)

**Comment by chochos** [comment]
Probably due to `Float` being native.

**Comment by FroMage** [comment]
Fixed!

**Comment by chochos** [comment]
Really? I pulled language module and js compiler (was up to date) and the test for this fails

**Comment by chochos** [comment]
ok tests pass now.
