### ISSUE TITLE
Error with `Array(1..4).keys.reversed`

### ISSUE THREAD

**Issue by quintesse** [ceylon/ceylon.language#733]
```ceylon
value foo = Array(1..4).keys.reversed;
```

gives

```
/opt/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150823-2253/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3601
']};});atr$(list$,'reversed',function(){var list$=this;return list$.Reversed$L
                                                                    ^
TypeError: Object [object Object] has no method 'Reversed$List'
    at $init$List.atr$.mod [as reversed] (/opt/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150823-2253/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:3601:932)
    at run (/home/tschotan/projects/ceylon/eclipse-workspace/JsTests/modules/test1/1.0.0/test1-1.0.0.js:13:106)
    at [eval]:1:279
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:559:25)
    at startup (node.js:80:7)
    at node.js:929:3
```

**Comment by quintesse** [comment]
`Array` just doesn't implement `List.reversed` as it should.

This seems like something that is bound to happen at other times as well when stuff gets added to `Iterable` or `List`, because the JS version of `Array` doesn't really inherit from from them so it doesn't automatically "pick them up".

Isn't there a test that could be made that will check that `Array` always implements all the methods from it's super classes/interfaces?

**Comment by quintesse** [comment]
Ok, maybe that's not the reason afterall, I'll shut up now and leave things to you @chochos  ;)

**Comment by FroMage** [comment]
After a lot of pain trying to figure out what happens, I have a hint:

what gets returned by `Array.keys` (a `List.Indexes`) only has the properties defined up until `List.Indexes` in the unit file: it doesn't have `List.Reversed` because it's after it. If I move ``List.Reversed` before `List.Indexes` then it works (but I assume the opposite won't work: `Array.reversed.keys` will fail).

So, even though I don't quite understand yet how prototype initialisation works in JS, I'm pretty sure it's that. Perhaps it all works if we move all member class prototype initialisation to the end, rather than one after the other?

**Comment by FroMage** [comment]
Yes, moving all calls of type `$init$Reversed$List();` to the end seems to work. I'll try to do that.

**Comment by FroMage** [comment]
Man, I feel like an adventurer, a space pioneer visiting a weird world.

**Comment by chochos** [comment]
welcome to my world

**Comment by FroMage** [comment]
Looks like I managed to fix this by adding an `InitDeferrer` object so that member types can add their init call in there and the containing class will use this after all its members have been visited.

**Comment by FroMage** [comment]
Now, how the hell do you test that sort of thing?

**Comment by FroMage** [comment]
I suppose I can test this in the language module tests…

**Comment by FroMage** [comment]
But it's not really meant for testing code generation. You have no runtime tests in the JS compiler?

**Comment by chochos** [comment]
well you can run `ant nodetest` and it will compile a bunch of Ceylon code then run it with `node`, including the language module tests.

**Comment by FroMage** [comment]
OK fine I'll find a place there. But I'll only be able to push tomorrow.

**Comment by FroMage** [comment]
Damn, looks like I only managed to fix this for classes, not interfaces nor objects. Oh well, more work ahead.

**Comment by chochos** [comment]
yes those are separate. Interfaces are generated in `TypeGenerator` and objects in in `Singletons` but it's the same principle.

**Comment by FroMage** [comment]
Fixed!

**Comment by FroMage** [comment]
Yes, why? They don't show up?

**Comment by chochos** [comment]
no, just asking. I hadn't seen the commit, nevermind.
