### ISSUE TITLE
Rename or add alias to `Number.magnitude`

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#734]
This morning @vietj and I looked for the absolute value of a number and it took us quite a while to find that we named that operation `magnitude`, which may be the proper mathematical term for it, but prevents non-math people, like most programmers, from ever finding it, because they will be looking for `absolute` or at least `abs[TAB]` with completion. This morning I had no idea that `magnitude` was a synonym for `absolute`. I suspect most programmers who are not experts in math will never find that.

We should at least add an alias like `shared default Other absolute => magnitude` so math-challenged people like us can find that thing.

Anyone else agree?

**Comment by gdejohn** [comment]
What about just changing the doc string from "The magnitude of this number, defined for any instance `x` as…" to "The absolute value of this number, defined for any instance `x` as…"

Then `Ctrl + F` "abs" on the API docs for Integer/Float/Number would get you right where you need to go.

**Comment by jvasileff** [comment]
I like @gdejohn's idea. `magnitude` seems Ceylonic to me, and I think the alternatives would have to be `absoluteValue` or `abs`.

**Comment by gavinking** [comment]
-1.

**Comment by FroMage** [comment]
Look, the same reasoning as for #730 goes here: don't make it hard for programmers that are not math experts, because I'm sure they're far more numerous than math experts.

I agree `abs` is against our naming convention. `absolute` may not be correct for real numbers, but I'm also pretty sure they not only make sense for `Integer` and `Float` but again, people expect them to be named like this because this is the norm and dialect in computer science. I'd be perfectly happy defining those aliases in those classes if we can't put them in `Number`, that's fine, really. As long as normal programmers can find them there that's all that counts. `absoluteValue` would also be fine, for the reasons you mention, not because it's pretty, but because people will _find_ them, with completion.

`magnitude` will just never be found, however correct it is in math, it's just unknown in computer science. This is not me trying to force you to make something wrong in math, this is just me thinking of programmers, most of whom have no background in math that will let them even know what the hell a magnitude is, like me, or Julien, and please accept it, countless others.

Again, an alias is fine.

**Comment by luolong** [comment]
@FroMage don't underestimate the ability of the "average" developer to learn some new terminology. 
I for one come from a non-English background and most of the keywords and functions I used in my early programs were just gobbledegook to me. 
I just knew that they did what I needed them to do and that was fine by me.

**Comment by lucaswerkmeister** [comment]
(By the way, commit 13b1e943f5ba4061c735b7906029d66342ef809d seems very relevant to this discussion.)

**Comment by FroMage** [comment]
It's one thing to learn new terminology, but another to forgo industry-wide and field-wide (CS, not math) conventions, which ensure that most experienced programmers who will look for `abs[TAB]` will be lost.

**Comment by vietj** [comment]
TBH, I could not find what I was looking for when I wanted to do it. So I ended up doing my own absolute function, believing it was not implemented.

Obviously `magnitude` is _ceylonic_ I would not expect less , but it's for from being _pragmatic_ at all!!!

**Comment by FroMage** [comment]
@gavinking am I allowed to add `shared Float absoluteValue => magnitude` to `Float`? That would make it much easier for CS people to find that, and it doesn't violate your objections.

**Comment by tombentley** [comment]
I don't really care whether this attribute is called `magnitude` or `absoluteValue`, but it's true that just about every other language calls it something like `abs`, so I think we should make it discoverable from that name via, at least,

* Autocomplete
* Ceylondoc search

Moreover I think it's common for the same concept to have multiple names (in any field, not just math/CS), so we need a general way to handle this. An alias would *work*, but clutters the API. A `synonym` doc annotation would be kinda neat, but require work.

**Comment by gavinking** [comment]
I think @tombentley's suggestion is _much_ better.

**Comment by gavinking** [comment]
Actually we already have a `tagged` annotation we could perhaps use. It's not like we've found any other use for it so far...

**Comment by FroMage** [comment]
I'm fine with a doc alias, but autocomplete/quick-fix has to handle it.

**Comment by FroMage** [comment]
Tags are for grouping, not aliases. We could use tags for basic types, streams, metamodel for example.

**Comment by tombentley** [comment]
> Tags are for grouping, not aliases. We could use tags for basic types, streams, metamodel for example.

Could you give an example, because I, like @gavinking, have never really known what that annotation is for.

**Comment by FroMage** [comment]
If we tag every type/function that deals with streams with the `Stream` tag, we can then select it in the ceylondoc and it will hide everything else. It's pretty neat.

**Comment by FroMage** [comment]
So the alias thing could be a lot of work in the IDE. I'm prepared to support it in the JVM backend and ceylondoc in time for 1.2. If @gavinking can make it work in the IDE I'll add support ASAP.

**Comment by gavinking** [comment]
@FroMage I think it can be implemented almost completely within `ceylon-model`, can't it? I don't think it requires any significant change to the IDE.

**Comment by FroMage** [comment]
How? If we want autocomplete and quick-fixes to make it work, how can the model loader handle this?

**Comment by gavinking** [comment]
The _model_, not the model loader. Autocompletion is implemented in the model.

**Comment by FroMage** [comment]
Oh, is it. Well, yes I suppose it would work there, then.

**Comment by gavinking** [comment]
> Well, yes I suppose it would work there, then.

Well, at least assuming we have not abused those APIs to do other stuff not related to completion. (We might have, FTR.)

**Comment by FroMage** [comment]
I assume you used the royal "we" there ;)

**Comment by gavinking** [comment]
I guess.

**Comment by FroMage** [comment]
Fixed.
