### ISSUE TITLE
infinity.powerOfInteger(0) on JS

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#740]
`infinity.powerOfInteger(0)` currently blows up. It should evaluate to `0.0`. Same with `(-infinity).powerOfInteger(0)`.

**Comment by FroMage** [comment]
I assume it should evaluate to `1.0` as for `power`, otherwise that'd be weird, no?

**Comment by gavinking** [comment]
Yeah. Sorry.

**Comment by FroMage** [comment]
Hah, `powerOfInteger` does not seem to exist in JS.
