### ISSUE TITLE
0.0^negativeNumber

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#741]
@lucaswerkmeister helpfully posted [this list of special cases](https://github.com/ceylon/ceylon.language/issues/737#issuecomment-137145871).

There is a detailed specification for what should happen with `0.0^y` where `y<0`. We have not really tested/documented our `Float` implementations for this case, and it looks like JS and Java behave differently.

We need to fix that.

**Comment by FroMage** [comment]
Well, that spec talks about "odd integer" cases, so I assume that only applies to integers? We never check for "odd" on floats, right?

**Comment by FroMage** [comment]
I think we should add something to `Float` to identify `-0.0`, as opposed to `0.0`. I haven't found any property which would tell me if it's that, and how to differentiate it from `0.0`, short of performing a division to check if its sign propagated.

**Comment by gavinking** [comment]
@FroMage well apparently they want us to distinguish "odd" integers from other FP numbers. Which of course is not even a really welldefined operation due to limited precision and rounding error. It seems pretty damn strange to me but that's what the spec seems to be saying.

**Comment by FroMage** [comment]
Well, unless they define this for `powerOfInteger`? And for `Float` exponents they are never `odd integer`?

**Comment by FroMage** [comment]
Isn't it great implementing a standard we don't have access to? :)

**Comment by gavinking** [comment]
Well they can be a number with an odd `wholePart` and a zero `fractionalPart`. It's rubbish but whatever.

**Comment by FroMage** [comment]
Dart seems indeed to consider `1.0` to be odd, but not `2.0` nor `1.1`. So indeed, it looks like we have to consider odd/even floats.

**Comment by gavinking** [comment]
Yeah, and if you take `1.0` and add `2.0` to it enough times, you are guaranteed to get an even number. Vomit.

**Comment by FroMage** [comment]
Well, actually we don't have to do anything on the JVM, because it already does the right thing.

**Comment by FroMage** [comment]
Done.

**Comment by gavinking** [comment]
Cool, thanks!
