### ISSUE TITLE
Add property to `Float` to distinguish `-0.0` from `+0.0`

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#742]
As noted in #741, sometimes we have to test things and make sure that we get a `-0.0` or a `+0.0` and since they are both `==` there's no way for us to check that they are the right zero, short of performing some formula. I think we should add something like `Boolean positiveZero` and `Boolean negativeZero` to `Float`.

OK?

**Comment by gavinking** [comment]
Can't you just check the `sign` of the number?

**Comment by FroMage** [comment]
Apparently not:

```
Produces `0.0` for `+0.0`,  `-0.0`, or undefined
```

**Comment by gavinking** [comment]
Ah no, sorry, that is `0.0` in both cases.

**Comment by gavinking** [comment]
Honestly I would prefer not to expose this. Why not just check that `string.startsWith("-")`?

**Comment by FroMage** [comment]
Why not? if `-0.0` is as important as `infinity` and `NaN` as special cases, why not let users check what they are without something as aweful as checking its string representation?

**Comment by FroMage** [comment]
Not exposing it only means people have to write the following _every time_ they care:

```ceylon
    Boolean positiveZero(Float num){
        return num == 0.0 && (1 / num) > 0.0;
    }
    Boolean negativeZero(Float num){
        return num == 0.0 && (1 / num) < 0.0;
    }
```

I don't see why we have to make it hard for them, even if they are few.

**Comment by gavinking** [comment]
Well I don't think it is important at all. I think it's an artefact of the bitwise representation that should never affect the program in any way.

The thing is, I think it's highly undesirable to have two values that are `==`, but distinguishable by another attribute.

**Comment by gavinking** [comment]
> Not exposing it only means people have to write the following _every time_ they care:

But they _never_ care.

**Comment by FroMage** [comment]
I assume all the people that deal with IEEE math care. Implementers of `ceylon.math` surely must care, for example. I suspect implementers of other numeric types that rely on `Float` will also care.

**Comment by FroMage** [comment]
> I think it's highly undesirable to have two values that are ==, but distinguishable by another attribute.

Well, we provide an IEEE implementation, not exact numbers, so it comes with special cases, compromises and special values, that we define publicly and follow, so I don't think that argument is valid. We define what happens with `-0.0` in the docs: it exists, it's specified. It don't understand why make it harder to distinguish it than `NaN` for example.

**Comment by gavinking** [comment]
After noticing that `-0.0` and `0.0` can already be distinguished using `(1.0/x).negative` I was about to say go ahead. But then I noticed that the feature you're asking for already exists, named `strictlyPositive` and `strictlyNegative`.

**Comment by FroMage** [comment]
Well, not really, that means `f == 0.0 && f.strictlyNegative` which is not much better.

**Comment by FroMage** [comment]
Am I allowed to add that `f == 0.0 && f.strictlyNegative` magical incancation to the `Float` API docs? Otherwise people looking for negative zero will be forced to come up with it by themselves over and over. If we're not allowed to tell them if it's a negative zero, at least we can tell them how to check for it correctly.

**Comment by gavinking** [comment]
Ah, sure, I guess so...

**Comment by FroMage** [comment]
Done.
