### ISSUE TITLE
strengthen contract for Set operations

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#744]
The `Set` operations `intersection`, `complement`, `exclusiveUnion`, etc. are not well defined considering the variety of valid `Set` implementations, which may lead to errors or confusion. Below is an explanation of the problem and a proposed solution.

**The Problem**

There are two basic issues:

- The return type `Set<Element&Other>` of `Set.intersection(other)` assumes an same-type requirement for `Contains` that does not exist.
- Set operations are defined in terms of `contains`, but `contains` has a very loose contract. For any given operation, there may be three different and incompatible definitions—that of the lhs, the rhs, and the result (usually `HashSet`).

Odd and unexpected results include:

```ceylon
    value hashFloat = HashSet { 1.0 };
    value hashInteger = HashSet { 1 };

    value singletonFloat = SingletonSet { 1.0; };
    value singletonInteger = SingletonSet { 1; };

    value treeFloat = TreeSet { uncurry(Float.compare); 1.0 };
    value treeInteger = TreeSet { uncurry(Integer.compare); 1 };

    print(hashFloat & hashInteger);                 // 1: AssertionError
    print(singletonFloat & singletonInteger);       // 2: {}

    print(treeFloat.exclusiveUnion(treeInteger));   // 3: { 1 }
    print(treeFloat.exclusiveUnion(hashInteger));   // 4: { 1 }
    print(hashFloat.exclusiveUnion(treeInteger));   // 5: { 1.0 }

    print(treeFloat | treeInteger);                 // 6: { 1 }
    print(treeFloat | hashInteger);                 // 7: { 1 }
    print(hashFloat | treeInteger);                 // 8: { 1 }

    print(hashFloat ~ treeInteger);                 // 9: { 1.0 }
    print(hashFloat.containsEvery(treeInteger));    //10: true!
    print(hashFloat ~ (treeInteger | treeInteger)); //11: {}
```

For 1 and 2, the result `{ 1.0 }` would be desirable given the definition of `contains` for `HashSet`s and `SingletonSet`s, but is not currently possible since `Float` is not assignable to `Float&Integer`.

Results 3, 4, and 5 are unreasonable: the exclusive union of two single-element sets cannot possibly be of size one.

Results 6, 7, and 8 are unreasonable in light of 3-5: the union of disjoint one-element sets should have two elements.

Results 9, 10, and 11 demonstrate a few more inconsistencies and confusion combining operations.

**Proposed Fix**

- Change the return type of `Set.intersection` to `Set<Element>`.
- Define all operations that combine or compare `Set`s in terms of `Object.equals`.

Conceptually, the elements of the lhs and rhs sets would be used to create new `HashSet`s lhs’ and rhs’ which would be used to perform the operation, thereby aligning the contract for `Contains` among the three sets (lhs’, rhs’, and result.)

While still *potentially* confusing when using `TreeSet`s and `IdentitySet`s, the behavior would be consistent and clearly documented.

**Additional Notes**

- Given that we will no longer rely on `rhs.contains`, the operations can be adjusted to accept arguments of `{Other*}` rather than `Set<Other>`. `Set<Other>` does not provide value beyond what `Iterable<Other>` offers—`Set<Other>` offers no guarantee against duplicate items in terms of the result set.
- For the common case of `HashSet`s, these changes will have an immeasurably small performance impact—just the addition of an `instanceof` test in the optimized code path.
- A more drastic (but potentially useful) change would be to move the set operations up to `Iterable`, since the the lhs `Set`’s definition of `contains` is also ignored. Of course, `HashSet` is not defined by the language module, so we’d lose our optimization.

**Comment by jvasileff** [comment]
I started on the first item

- https://github.com/jvasileff/ceylon-spec/commits/set-intersections
- https://github.com/jvasileff/ceylon.language/commits/set-intersections
- https://github.com/jvasileff/ceylon-sdk/commits/set-intersections

before realizing a bigger change might be necessary.

**Comment by gavinking** [comment]
> Change the return type of `Set.intersection` to `Set<Element>`.

Well, actually my preference would be the exact opposite: change the implementation of `XxxxSet.intersection()` to eliminate every element which isn't an instances of the type `Element&Other`.

`HashSet` already has an `assert` there which could be changed to an `if`, and then that could be propagated to the other implementations of `Set`.

**Comment by lucaswerkmeister** [comment]
I think there are two problems here:

- `Float` and `Integer` violate this recommendation from `Object.equals`:
  
  > Furthermore it is recommended that implementations
     ensure that if `x==y` then `x` and `y` have the same 
     concrete class.
  
  For sets based on equality, this is a problem, since they can now be expected to contain objects that don’t fit in them based on their type.

- You’re combining sets with different meanings, some based on equality, others based on identity. There can’t be any correct results for this.

I don’t think these are problems of `Set`, though, so I don’t think the `Set` contract needs to be adjusted to fix them.

**Comment by jvasileff** [comment]
@lucaswerkmeister 

I agree there is no perfect answer. In fact, it's logically impossible to take a union of two `TreeSet`s—comparators can neither be compared nor combined. Nevertheless, these operations are defined at the `Set` level, and we're not throwing `UnsupportedOperationException`s. So we should make the best of it. (Currently `HashSet`s are used for unions of `TreeSet`s, as in the proposal.)

Regarding `equals`, we can't just code to the level of what's recommended, at least when 1) we have a way to do better, and 2) the recommendation is often ignored, e.g. numbers, `List`s, and real world code, such as with `Person`, `Student`, and `Staff` with primary key based equality.

Regarding identity, I haven't picked on `IdentitySet`s yet! But at least on their own, they're probably consistent.

> I don’t think the Set contract needs to be adjusted

You didn't offer a reason why the proposal makes things worse, nor did you reject its benefits.

@gavinking 

I don't see how it's reasonable for two non-empty and equal `Set`s to have an empty intersection (which we had until a recent commit); I'd much prefer the current runtime error.

Although I like the idea of `Set<Element&Other>`, it's only correct today for `IdentitySet`.

Another approach for consistent `Set` operations would be to have a `TypeCheckingHashSet` that defines `contains` in terms of `equals` + a type check, and use that for the lhs', rhs', and result sets. But it would be slow and produce unexpected results for people used to `HashSet`s.

**Comment by gavinking** [comment]
> I don't see how it's reasonable for two non-empty and equal `Set`s to have an empty intersection (which we had until a recent commit); I'd much prefer the current runtime error.

Well personally I think that's perfectly fine. As long as we define that.

**Comment by gavinking** [comment]
> Another approach for consistent Set operations would be to have a `TypeCheckingHashSet` that defines `contains` in terms of `equals` + a type check, and use that for the lhs', rhs', and result sets

Yes I toyed with that idea but I'm concerned about the performance implications of that.

**Comment by FroMage** [comment]
Is that really for 1.2?

**Comment by gavinking** [comment]
Yes.

**Comment by gavinking** [comment]
This is now fixed, with no negative impact upon performance.

Thanks @jvasileff.
