### ISSUE TITLE
Class.getDeclaredAttribute() with non-shared attributes

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#746]
It seems that `Class.getDeclaredAttribute()` with a non-`shared` attribute returns null, but `Class.getDeclaredMethod()` with a non-`shared` method returns the method model. Surely this is a bug.

**Comment by FroMage** [comment]
Fixed for JS, and added tests. On the JVM this was actually working for captured attributes, which is the only case where the metamodel may come in useful so we were already covered.
