### ISSUE TITLE
Add alias annotation

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#751]
To solve `undefined`/`notANumber` and `magnitude`/`absolute` as discussed in #734 and #730.

**Comment by FroMage** [comment]
I suppose something like:

```
interface Number {
// ...
    "The magnitude of this number, defined for any instance 
     `x` as:
     
     - `-x` if `x<0`, or 
     - `x` otherwise,
     
     where `0` is the additive identity. Hence:
     
     - `x.magnitude >= 0` for any `x`, and
     - `x.magnitude == 0` if and only if `x==0`."
    aliases("absolute")
    shared default Other magnitude
            => negative then negated else this of Other;
}
```

Where we make `aliases` accept more than one string?

**Comment by tombentley** [comment]
Should it be `aliases` (an `OptionalAnnotation`) or should we use a `SequencedAnnotation`. I sort-of think having multiple annotations looks better in this case. But then `alias` is a keyword, so we'd have to use `synonym` or somesuch.

**Comment by gavinking** [comment]
aliased("absolute")

Or

    aliased("modulo", "remainder")

**Comment by FroMage** [comment]
OK I've added it in the model and the model loader. It shows up in completions in the IDE, but only when you have started typing it, and then it doesn't show why it's not listing `absolute` when I type `abs` and why it shows `magnitude`. I think we should add some visual clue to `magnitude` in this case, probably by listing the matching alias (or possibly all its aliases)? That's IDE work.

I also think we should add duplicate results for each alias, because when I complete on a number and no prefix, I get all members, but sorted and `absolute` is not listed, leading users to stop searching. If we could list something like `absolute -> magnitude` that'd be enough. I _think_ this is IDE work too.

And finally I didn't set the aliases during typechecking, because I did not find where the typechecker knows that `aliased` is `ceylon.language::aliased` and not some other annotation, when looking at annotations. Can you add the right typechecker incantation when we're not loading from the classes, @gavinking?

Then I'll work on ceylondoc support. There also I will list virtual entries for the aliases in the respective category they represent (field, method, type), to point to the aliased declaration.

**Comment by FroMage** [comment]
Done in the IDE. Still waiting for an answer on how I can load this annotation in the typechecker @gavinking. You can try it out, though. Now on to ceylondoc.

**Comment by lucaswerkmeister** [comment]
I don’t understand what you want to add to the typechecker… do you mean that it should be legal to actually write `i.absolute` instead of `i.magnitude`?

**Comment by FroMage** [comment]
No, I mean that the model has an extra `aliases` field which needs to be populated by the typechecker. I haven't found how to do that.

ATM it's only populated by the model loader.

**Comment by lucaswerkmeister** [comment]
Okay, good.

**Comment by FroMage** [comment]
OK done for the typechecker and ceylondoc, but please review the typechecker part @gavinking.
