### ISSUE TITLE
Add tags to categorize the module

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#753]
We should try the tag functionality we've added in ceylondoc _for that very purpose_. It allows us to filter the doc based on categories, such as basic types, numbers, streams, functions.

To kick-start the discussion and illustrate what this does, I'll add a commit so you can run `and doc` and check the results in the generated API docs in `Filters` (top-right menu). If you guys agree, feel free to suggest categories and members (or just do it). If you disagree we can always revert my commit. But PLEASE try it out, it's pretty neat.

**Comment by tombentley** [comment]
When I click on "Basic types" I get taken to the search page with "Basic%20types" in the input and no results.

Also, I want a tag cloud.

**Comment by tombentley** [comment]
> Also, I want a tag cloud.

It doesn't lamely have to use a bigger font for more popular tags though.

**Comment by tombentley** [comment]
Oh, and finally, it *might* be useful to issue a warning about tags with only one member (that will tend to catch typos, for instance), and a tag with only one thing is a bit pointless.

Apart from these things it seems vaguely useful.

**Comment by FroMage** [comment]
What? I don't get to the search page by clicking `Basic types`, that's really weird.

**Comment by lucaswerkmeister** [comment]
Are tags on modules supported? The `ceylon.html` module descriptor is `tagged` – the only use of `tagged` in language module and SDK I could find yesterday – but I don’t see the tags anywhere on the Herd.

**Comment by FroMage** [comment]
Oh, when you click on the tag, not the menu. Yes that's a bug.

**Comment by FroMage** [comment]
> Are tags on modules supported?

If not, they should be.

**Comment by tombentley** [comment]
> Oh, when you click on the tag, not the menu

The *menu*?... Ah the filter thing you mean? I didn't even spot that, it's not obvious at all. Should it have an "untagged" option?

**Comment by FroMage** [comment]
> check the results in the generated API docs in Filters (top-right menu)

:(

That's the _only_ place where this feature shines. It's extremely nice IMO.

> Should it have an "untagged" option?

Good question. I am not sure it'd be very useful.

**Comment by tombentley** [comment]
So what other tags do we need for the language module?

* Sorting? (for stuff to do with comparing and comparators)
* Operator? (for methods used to define operators)

Any others?

Also I can't help but feel we'll one day want a refactoring to change a tag, but that's another issue I guess.

**Comment by FroMage** [comment]
> Sorting, Operator

Both good ideas IMO.

@gavinking any opinion?

**Comment by gavinking** [comment]
The major categories are: numbers, streams, collections, sequences, strings, functions, environment.

**Comment by FroMage** [comment]
Not operators?

**Comment by FroMage** [comment]
And metamodel and serialisation I guess.

**Comment by gavinking** [comment]
Um. Not really...

**Comment by gavinking** [comment]
Yes, meta and serialization of course.

**Comment by FroMage** [comment]
Added tags everywhere, and added the `Comparisons` tag to the list, since we had lots of stuff for that.

Remaining untagged things:

- `default`, `abstract` annotations and the rest, I suggest a `Language annotations` tag or something
- `doc`, `deprecated` annotations and the rest, I suggest a `Documentation` tag,
- `Range`, `Measure` and stuff that I just don't know how to categorise,
- `Annotated`, `Annotation`, `ConstrainedAnnotation` and stuff, perhaps `Annotations` tag?
- `Binary` (no idea, seems alone),
- `Enumerable` again no idea,
- `Contextual` no idea,
- `identityHash` no idea

Any idea/comment?

**Comment by FroMage** [comment]
Well, if nobody has comments, let's just close this as good enough until someone becomes interested again.
