### ISSUE TITLE
Add Integral.modulo

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#755]
In Ceylon, the result of `remainder()` takes the sign of the dividend:

    -10 % 7 = -3

An alternate interpretation is sometimes useful, where the result is always positive:

    -10 mod 7 = 4

For reference, Java's `BigInteger` offers both [remainder](http://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#remainder-java.math.BigInteger-) and [mod](http://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#mod-java.math.BigInteger-).

For completeness and consistence with `Whole`, it may make sense to add `Integral.modulo`. Description/possible implementation:

```ceylon
        if (!modulus.positive) {
            throw AssertionError("modulus must be positive");
        }
        return let (result = remainder(modulus))
               if (result.negative)
               then result + modulus
               else result;
```

**Comment by FroMage** [comment]
+1

**Comment by gavinking** [comment]
+1

**Comment by FroMage** [comment]
Done.
