### ISSUE TITLE
Float.equals/Integer.equals violate transitivity constraint

### ISSUE THREAD

**Issue by ePaul** [ceylon/ceylon.language#758]
**Summary**
During the review of #756 I noted that Integer.equals/Float.equals in some cases violate the transitivity constraint from Object.equals.

**Details**
It looks like the definitions of [Float.equals][1] and [Integer.equals][2] were carefully worded in order to allow integers to be equal to some float number, while still fulfilling the general contract of [Object.equals][3] (apart from the reflexivity constraint with NaN, which is explicitly mentioned as a violation).

But in the JVM, the implementations don't hold that promise. Here we have three numbers which violate the transitivity:

```ceylon
    value y = 9.2233720368547763E17;
    value x = y.integer;
    value z = x + 1;
    assert(x == y);
    assert(y == z);
    assert(x != z);
```

*(In the JavaScript implementation (I tried the web runner), `x` and `z` are both 922337203685477600 and equal to `y`, which seems even more strange, but at least the transitivity is fulfilled.)*

In the JVM, `x == 922337203685477632` and `z == 922337203685477633`.

There are many more of such triples, all integers beyond the ±2^53 limit show this with at least one of their predecessor or successor (often both). (Those integers can't be converted directly to floats by their `.float` attribute (this throws an OverflowException), but by adding `0.0` to them.)

The reason is that the implementation (in both Float.java and Integer.java) just uses the primitive Java  `==` operator on a `double` and a `long`, and this will convert the `long` to `double`, loosing precision (i.e. the same happens in Java when using primitive `long` and `double`), like this:

```java
static boolean equals(long integerValue, double floatValue) {
    return (double)integerValue == floatValue;
}
```
(The cast is not needed, is will implicitly done by the `==` operator. I just added it for clarity.)

I think a good fix would be to check in the equals comparison whether the Float value maps back to this Integer value, in effect selecting only one of the multiple Integers which map to the same Float as "the" equal one:

```java
static boolean equals(long integerValue, double floatValue) {
    return (double)integerValue == floatValue && (long)floatValue == integerValue;
}
```

The effect would be that the `y == z` equality in the example above is not valid, too, so no transitivity break.

If wanted, I can submit a pull request which fixes this by changing Integer.equals and Float.equals accordingly.

[1]: https://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/Float.type.html#equals
[2]: https://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/Integer.type.html#equals
[3]: https://modules.ceylon-lang.org/repo/1/ceylon/language/1.1.0/module-doc/api/Object.type.html#equals

**Comment by gavinking** [comment]
OK, so I think I agree that if we have a floating point number whose magnitude is larger than `9007199254740991.0` then it should not be considered equal to any `Integer`. 

It sounds especially reasonable in light of the fact that those are the cases where `Integer.float` throws.

**Comment by ePaul** [comment]
> OK, so I think I agree that if we have a floating point number whose magnitude is larger than  `9007199254740991.0`  then it should not be considered equal to any  `Integer`.

That was not exactly what I was proposing, though ... but for better interoperability with the JavaScript implementation this might be better than having some Integer values in this range equal to some Float values and some not?

> It sounds especially reasonable in light of the fact that those are the cases where  Integer.float  throws.

In #759 I am proposing to actually make Integer.float not throw an exception when there is an exact representation as Float possible (and in those cases the Integer and Float value would be equal in my proposal).

These are actually the values which result from `Float.integer`, so this would make this more symmetric.

**Comment by gavinking** [comment]
> this might be better than having some Integer values in this range equal to some Float values and some not?

I think it's "good enough", and easier to understand / reason about.

**Comment by gavinking** [comment]
This was fixed by @ePaul's PR. Good work mate!
