### ISSUE TITLE
fix docs for serialization package

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#760]
The docs and code examples for the serialization package are totally outdated and refer to nonexistent members and types. We need to fix this urgently.

**Comment by tombentley** [comment]
I thought I'd already reviewed this stuff, so to be sure: which docs are you referring to?

**Comment by gavinking** [comment]
@tombentley well as a starting point just try building and look for the warnings!

**Comment by tombentley** [comment]
Warnings have been fixed. Please reopen if there are other things wrong or out of date.

**Comment by gavinking** [comment]
Well there is still a code example which calls `DesrializationContext.instance()` with one argument. It looks like you fixed _some_ of the problems with that code example, but did you actually test that it compiles and runs?

**Comment by tombentley** [comment]
Ah, OK, thanks.

This is a general problem though: There's a lot of example code (e.g. in the metamodel) some of which is bound to be wrong, but it's a *lot* of work to go through it and check, and it's the sort of thing which ought to be automated. python has doctest for example.
