### ISSUE TITLE
experiment with sum()/product() optimization for min()/max()

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#773]
@jvasileff you had a nice test performance harness in #728.

Would you do us a favor and check if the same performance optimization that worked for `sum()` and `product()` would also work for `min()` and `max()`?

**Comment by jvasileff** [comment]
Sure, it looks like an interesting test. I'd actually like to see no improvement, which would support the notion of a "never unbox" compiler strategy.

**Comment by quintesse** [comment]
@jvasileff I actually went quite some way into implementing the basis needed for that. It lets you choose boxing strategies depending on the actual *usage* of the boxed values.
I made it at least as far that changing the boxed/unboxed state of a value doesn't affect the workings of the code (before that many things were often assumed to be boxed/unboxed without actually checking) but I failed to come up with a good strategy that resulted in an improvement in all cases unfortunately. (But that's just me, I'm sure it has to be possible)

**Comment by jvasileff** [comment]
@quintesse I haven't tested performance yet, but I've been doing a dumb version of that for Dart, like flagging loop variables in for-fail to not unbox. It's hard to imagine that once you have an `Integer`, it's *that* expensive to extract the primitive.

**Comment by quintesse** [comment]
> I've been doing a dumb version of that for Dart, like flagging loop variables in for-fail to not unbox

You can test something like that in Ceylon by passing `-Dceylon.compiler.forceBoxedLocals` , it was part of the changes I made to test if everything kept working (eg. compile the SDK with that and run the tests).

> It's hard to imagine that once you have an Integer, it's that expensive to extract the primitive.

Sure, but if you never need the boxed value you should also not create it. So you need to be smart about it. Which is what I was trying to do.

**Comment by jvasileff** [comment]
> if you never need the boxed value you should also not create it

Right. But with for-fail you're guaranteed to be boxed since the source is generic. And for narrowing operations (is/exists/if/switch) you know that you already have a "wide" instance, so there *might* be no advantage in making replacement declarations.

`variable`s should of course always be primitive.

**Comment by quintesse** [comment]
> variables should of course always be primitive.

Why? If the source is boxed why unbox?

Btw, I just pushed the branch I was testing this with in case you want to take a look at what I was doing:

https://github.com/ceylon/ceylon-compiler/commit/d31a5453449bb4beedd0dfab41b42e580cb8ec8c

It's a visitor that counts the number of times a local value is wanted boxed or unboxed (in case you want to let's say equate 5 unboxed uses as a single boxed one, in my test strategy I just let a single boxed usage win out over any number of unboxed usages).

**Comment by jvasileff** [comment]
> Why? If the source is boxed why unbox?

Ok, yeah, I guess it could go either way depending on the consumers of the value.

> I just pushed the branch

cool, I'll take a look.

**Comment by gavinking** [comment]
@quintesse that's a really good ides.

**Comment by quintesse** [comment]
Yeah the basic idea is pretty neat, but I just couldn't get it to work Just Right, and after spending way too much time on it (back in the beginning of the year) I decided to let it lie for a while for when I have some more time to think about it / tinker with it.

**Comment by quintesse** [comment]
> but I just couldn't get it to work Just Right

Btw, it *does* work, nothing breaks, but just as there were cases it obviously improved there were some other cases it made worse and I just couldn't get the heuristics right to only keep the good ones and get rid of the bad ones.

**Comment by gavinking** [comment]
Right, that's the tricky bit, naturally.

**Comment by quintesse** [comment]
Oh btw @jvasileff you can also play around with boxing / unboxing right now in the current compiler (no need for that branch) by adding either `@boxed` or `@unboxed` to a declaration. This even works for methods and attributes. These are just for playing around of course and you'll get "compiler annotations are not a supported feature" messages. But together with `--verbose=code` it's an invaluable tool to see what the changing of the boxing state of a declaration does to the generated code.

**Comment by jvasileff** [comment]
Ok, so there is a marked improvement with the "optimized" code for `min()`. I think I'd have to spend time working with the compiled Java code though to draw any conclusions from this re our boxing discussion.

The results (including a strange ints-1 results):

### Integers (counting up)
```
Summary min/max/avg/rstddev/pct
lang::min(ints); size=1: 76/79/77/1% (100%)
optimized(ints); size=1: 115/127/122/3% (152%)

Summary min/max/avg/rstddev/pct
optimized(ints); size=8: 43/47/45/3% (100%)
lang::min(ints); size=8: 55/57/56/0% (127%)

Summary min/max/avg/rstddev/pct
optimized(ints); size=256: 33/36/35/4% (100%)
lang::min(ints); size=256: 49/51/50/2% (147%)

Summary min/max/avg/rstddev/pct
optimized(ints); size=1024: 33/35/34/3% (100%)
lang::min(ints); size=1024: 49/51/50/1% (149%)
```
### Integers (counting down)
```
Summary min/max/avg/rstddev/pct
lang::min(ints); size=1: 75/77/76/1% (100%)
optimized(ints); size=1: 95/101/98/2% (127%)

Summary min/max/avg/rstddev/pct
optimized(ints); size=8: 47/56/50/6% (100%)
lang::min(ints); size=8: 60/67/62/4% (126%)

Summary min/max/avg/rstddev/pct
optimized(ints); size=256: 36/38/37/2% (100%)
lang::min(ints); size=256: 50/57/53/5% (138%)

Summary min/max/avg/rstddev/pct
optimized(ints); size=1024: 34/36/35/1% (100%)
lang::min(ints); size=1024: 48/51/49/1% (140%)
```
### Floats (counting up)
```
Summary min/max/avg/rstddev/pct
optimized(floats); size=1: 76/77/77/0% (100%)
lang::min(floats); size=1: 78/82/80/1% (102%)

Summary min/max/avg/rstddev/pct
optimized(floats); size=8: 48/49/48/0% (100%)
lang::min(floats); size=8: 64/67/65/2% (132%)

Summary min/max/avg/rstddev/pct
optimized(floats); size=256: 34/36/35/2% (100%)
lang::min(floats); size=256: 58/69/61/7% (169%)

Summary min/max/avg/rstddev/pct
optimized(floats); size=1024: 35/36/36/1% (100%)
lang::min(floats); size=1024: 60/62/61/1% (168%)
```
### Floats (counting down)
```
Summary min/max/avg/rstddev/pct
optimized(floats); size=1: 75/76/76/0% (100%)
lang::min(floats); size=1: 78/82/80/1% (104%)

Summary min/max/avg/rstddev/pct
optimized(floats); size=8: 46/48/47/1% (100%)
lang::min(floats); size=8: 78/81/80/1% (168%)

Summary min/max/avg/rstddev/pct
optimized(floats); size=256: 34/37/36/2% (100%)
lang::min(floats); size=256: 77/90/81/6% (223%)

Summary min/max/avg/rstddev/pct
optimized(floats); size=1024: 34/36/35/2% (100%)
lang::min(floats); size=1024: 77/80/79/1% (227%)
```

And the test code:

```ceylon
shared Absent|Value minOptimized<Value,Absent>
        (Iterable<Value,Absent> values)
        given Value satisfies Comparable<Value>
        given Absent satisfies Null {

    value it = values.iterator();
    value first = it.next();
    if (is Integer first) {
        variable Integer min = first;
        while (is Integer val = it.next()) {
            if ((val of Integer) < min) {
                min = val;
            }
        }
        assert (is Value result = min);
        return result;
    }
    else if (is Float first) {
        variable Float min = first;
        while (is Float val = it.next()) {
            if ((val of Float) < min) {
                min = val;
            }
        }
        assert (is Value result = min);
        return result;
    }
    else {
        return nothing;
    }
}

shared void minTest() {
    for (size in [1, 8, 256, 1024]) {
        value ints = (1..size).reversed.collect(identity);
        value floats = (1..size).reversed.collect(Integer.float);
        value repeat = 2^28 / size; // 2^25 for floats, 2^28 for ints

        print(min(ints));
        print(minOptimized(ints));

        print(min(floats));
        print(minOptimized(floats));

        print(type(ints));

        //benchmark {
        //    scale = repeat * size  / 10;
        //    warmupIter = 3;
        //    benchIter = 5;
        //    ["lang::min(ints); size=``size``:", () => (0:repeat).each((_) => min(ints))],
        //    ["optimized(ints); size=``size``:", () => (0:repeat).each((_) => minOptimized(ints))]
        //};

        benchmark {
            scale = repeat * size  / 10;
            warmupIter = 3;
            benchIter = 5;
            ["lang::min(floats); size=``size``:", () => (0:repeat).each((_) => min(floats))],
            ["optimized(floats); size=``size``:", () => (0:repeat).each((_) => minOptimized(floats))]
        };
    }
}
```

**Comment by gavinking** [comment]
So we should make this same optimization then?

You want to send a PR or you want me to copy/paste?

**Comment by jvasileff** [comment]
copy & paste sounds good to me.

**Comment by gavinking** [comment]
OK, done, thanks!
