### ISSUE TITLE
Add type function support to JVM backend

### ISSUE THREAD

**Issue by luolong** [ceylon/ceylon.language#774]
type functions are implemented as an experimental unofficial feature on js backend, but much of the work I do is mostly on JVM and I would love to experiment with type functions in libraries.

I suspect that many libraries could benefit from these. Things like typesafe fluent assertion frameworks and web service routing libraries, serializers, etc.

**Comment by tombentley** [comment]
I dabbled a little in this a month or two ago, trying to get some of the blogged examples to work,  but got to the stage where (a) I needed to ask @gavinking a few questions and (b) it was wasn't justifiable for 1.2.

**Comment by gavinking** [comment]
@luolong did you mean to report this against `ceylon.language`? This is for `ceylon-compile`, no?

**Comment by FroMage** [comment]
Yeah, this is for the backend and for 1.3, closing.

**Comment by luolong** [comment]
@gavinking yes, I meant for ceylon-compiler backend. Should I re-submit it there?

**Comment by gavinking** [comment]
Yes.

**Comment by luolong** [comment]
new issue is ceylon/ceylon-compiler#2358

**Comment by FroMage** [comment]
Thanks
