### ISSUE TITLE
Metamodel: functional parameters broken?

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#783]
In the tests when we visit `Iterable` on JS I see:

```ceylon
 Iterable<Result, Absent> map<Result>(Callable<Result, Tuple<Element, First, Rest>> collecting());
```

Where the real signature is:

```ceylon
    Iterable<Result,Absent> map<Result>(
            "The mapping to apply to the elements."
            Result collecting(Element element)) 
```

So I know the first issue is already reported as #782, but the function declaration appears to have zero parameters and return a `Callable`, which is wrong.

**Comment by FroMage** [comment]
Let me try to see if I can make sense of this.

**Comment by FroMage** [comment]
So first, the metamodel info does not contain the functional parameter names:

```javascript
iterable$.$_map.$crtmm$=function(){
 return { 
  mod:$CCMM$,
  $t:{t:Iterable,a:{Absent$Iterable:'Absent$Iterable',Element$Iterable:'Result$map'}},
  ps:[
   {nm:'collecting',
    mt:'prm',
    $pt:'f',
    $t:{t:Callable,a:{Return$Callable:'Result$map',Arguments$Callable:{t:'T',l:['Element$Iterable']}}},
    an:function(){return[doc("The mapping to apply to the elements.")];}
    }],
  $cont:Iterable,
  tp:{Result$map:{}},
  pa:9,
  an:function(){return[doc$($CCMM$,'$:Iterable:$m:map'),see([$init$OpenFunction$jsint()(lmp$(ex$,'$'),$init$Iterable().$$.prototype.collect)].$sa$({t:Declaration$meta$declaration}))];},
  d:['$','Iterable','$m','map']};
};
```

**Comment by chochos** [comment]
you can probably retrieve that from the model

**Comment by FroMage** [comment]
Yeah, the model contains it:

```
map:{
 $t:{
  tp:[
   {
    mt:"tp",
    nm:"Result"
   }
  ],
  pk:".",
  nm:"Singleton"
 },
 pa:3,
 mt:"m",
 tp:[
  {
   nm:"Result"
  }
 ],
 ps:[
  [
   {
    $t:{nm:"Result"},
    mt:"prm",
    $pt:"f",
    ps:[
     [
      {
       $t:{nm:"Element"},
       mt:"prm",
       nm:"e"
      }
     ]
    ],
    nm:"collecting"}
  ]
 ],
 nm:"map"}
```

**Comment by FroMage** [comment]
But you're saying I should get it from the model, not add it to the metamodel info? What's the rationale?

**Comment by chochos** [comment]
the runtime metamodel info contains mostly type info. It says the parameter is functional and contains its type (a Callable that returns a Result and receives an Element). The name is not really important; what's needed is just to print the parameters of the Callable type, which can be called p0, p1, etc.

**Comment by chochos** [comment]
This is just printing, really.

**Comment by FroMage** [comment]
OK fine.

**Comment by FroMage** [comment]
Well it's not just printing, it needs the types of the parameters too, and possibly those parameters can also be functional. Anyways I found the model info and I get `[{"$t":{"pk":".","nm":"Character"},"mt":"prm","nm":"element"}]` for the param list, but apparently when I call `FunParamDecl(this,p)` on it I get: `ceylon.language::NativeError "Error: Missing type argument 'Type' [object Object]"` which is not helpful (as always) since there's no stack trace.

**Comment by FroMage** [comment]
Ah, here we go, the stack trace:

```
[ceylon-run-js] Error: Missing type argument 'Type' [object Object]
[ceylon-run-js]     at typeLiteral$meta (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:5426:7)
[ceylon-run-js]     at _openTypeFromTarg (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:7100:7)
[ceylon-run-js]     at $init$ValParamDecl$jsint.atr$.mod [as openType] (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.2.0/ceylon.language-1.2.0.js:10106:8)
[ceylon-run-js]     at visitParameter (/home/stephane/src/java-eclipse/ceylon.language/build/test/metamodel/0.1/metamodel-0.1.js:11784:19)
```

**Comment by FroMage** [comment]
At this point I'm in WAY out of my head.

**Comment by FroMage** [comment]
OK, I added it in the metamodel generator and it Just Works.
