### ISSUE TITLE
confusing error message for parseFloat() failures

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#785]
`parseFloat(2.7182818284590452354)` on the JVM results in:

```
ceylon compile-dart: 8736074210880900738 cannot be coerced into a 64 bit floating point value
ceylon.language.OverflowException "8736074210880900738 cannot be coerced into a 64 bit floating point value"
    at ceylon.language.Integer.getFloat(Integer.java:442)
    at ceylon.language.parseFloat_.parseFloat(parseFloat.ceylon:86)
```

which complicates troubleshooting (trying to find source data that aligns with `8736074210880900738`). I'm guessing this is an unintended consequence of https://github.com/ceylon/ceylon.language/pull/756.

cc @ePaul

**Comment by gavinking** [comment]
@jvasileff do you agree with @c8d4ddf?

**Comment by jvasileff** [comment]
Oh, yeah, I forgot about `nearestFloat`. But the patch doesn't look good:

```ceylon
shared void run() {
    print(parseFloat("3.14159265358979323846")); // <null>
    print(parseFloat("2.7182818284590452354")); // 0.8736074210880901
}
```

and `<null>`, `<null>` on JS.

**Comment by jvasileff** [comment]
BTW - I guess I hastily read the stack trace before. The error in *Integer* isn't confusing as long as you notice it's coming from `Integer.getFloat` and not `parseFloat`.

**Comment by gavinking** [comment]
Pfffff.

```
public class Java {

    public static void main(String[] args) {
        System.out.println(Double.parseDouble("2.7182818284590452354"));
    }

}
```

Output:

     2.718281828459045

**Comment by gavinking** [comment]
Fixed!

This implementation is _much_ better :-)
