### ISSUE TITLE
late should be constrained to ReferenceDeclaration

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon.language#787]
Now that we have `ReferenceDeclaration` shouldn't `late` and `variable` be constrained to it, rather than to `ValueDeclaration`?

**Comment by gavinking** [comment]
I guess `late` could be, but not `variable`, since it can be applied to `formal` declarations.

**Comment by FroMage** [comment]
Let's close this if we're going to remove `ReferenceDeclaration`, no?

**Comment by gavinking** [comment]
@FroMage yes, +1.

**Comment by FroMage** [comment]
But then => #788
